@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

autonumber

title Sequence Diagram of `schedule /clear` Command

actor   User
participant "werkIt:WerkIt" AS WerkIt

participant "newCommand\n:ScheduleCommand" AS newCommand
participant "dayList\n:DayList" AS DayList
participant "ui:UI" As UI

activate WerkIt
ref over WerkIt
Obtain and parse user input
end

WerkIt -> newCommand : execute()
activate newCommand

newCommand -> DayList : clearDayPlan(userArgument)
activate DayList
create "Integer" AS int
DayList -> int: parseInt(userArgument)
DayList <-- int : dayNumber: int

create InvalidScheduleException AS ise
opt !isDayValid
DayList -> ise : throw new InvalidScheduleException
activate ise
return
deactivate ise
end
DayList -> DayList : clearPlan(dayNumber)
activate DayList
return
DayList -> DayList : covertDayNumberToDay(dayNumber)
activate DayList
return dayName:String
DayList -> UI : printClearedScheduleOnADay(dayName)
deactivate DayList
activate UI
UI--> User: Print successfully remove \nplan from schedule message
deactivate UI

participant "fileManager:FileManager" as FileManager
newCommand -> FileManager : rewriteAllDaysScheduleToFile(newDay)
activate FileManager
ref over FileManager
Write the plans scheduled
for the week into 'schedule.txt'
file on user's system.
end
newCommand <-- FileManager
deactivate FileManager

destroy newCommand
@enduml