@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

autonumber

title Sequence Diagram of `schedule /clearall` Command

actor   User
participant "werkIt:WerkIt" AS WerkIt
participant "ui:UI" AS UI
participant "newCommand\n:ScheduleCommand" AS newCommand
participant "dayList\n:DayList" AS DayList


activate WerkIt
ref over WerkIt
Obtain and parse user input
end

WerkIt -> newCommand : execute()
activate newCommand

newCommand -> DayList : clearAllSchedule()
activate DayList
loop 7 times
DayList -> DayList : clearPlan(dayNumber)
activate DayList
return
end
deactivate DayList

newCommand -> UI : printClearedScheduleMessage()
activate UI
UI --> User: Display a message to \nindicate the process is completed
deactivate UI

participant "fileManager:FileManager" as FileManager
newCommand -> FileManager : rewriteAllDaysScheduleToFile(newDay)
activate FileManager
ref over FileManager
Write the plans scheduled
for the week into 'schedule.txt'
file on user's system.
end
newCommand <-- FileManager
deactivate FileManager

destroy newCommand
@enduml