@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

hide footbox
autonumber

title Sequence Diagram of `schedule /list` Command

participant "werkIt:WerkIt" AS WerkIt COLOR_WERKIT
participant "newCommand\n:ScheduleCommand" AS newCommand COLOR_LOGIC
participant "dayList\n:DayList" AS DayList COLOR_LOGIC


activate WerkIt COLOR_WERKIT
ref over WerkIt
Obtain and parse user input
end

WerkIt -> newCommand : execute()
activate newCommand COLOR_LOGIC

newCommand -> DayList : printSchedule()
activate DayList COLOR_LOGIC
loop 7 times

DayList -> DayList : padWithSpaces(planForDay)
activate DayList COLOR_LOGIC
return planForDayWithPadding:string

end
WerkIt <-- DayList : Display plans scheduled for the week
return
destroy newCommand
@enduml