@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml
hide footbox

autonumber

Participant ":WerkIt" as WerkIt #Sandybrown
Participant ":UI" as UI #YellowGreen
Participant ":Parser" as Parser #Gold
Participant ":Storage" as Storage #IndianRed

activate WerkIt #Sandybrown
WerkIt -> UI : getUserInput()
activate UI #YellowGreen
return "workout /new sit up /reps 5"
deactivate UI

WerkIt -> Parser : parseUserInput("workout /new sit up /reps 5")
activate Parser #Gold

create ":Logic" as Logic #LightSkyBlue
Parser -> Logic : new WorkoutCommand()
activate Logic #LightSkyBlue
return :WorkoutCommand

Parser --> WerkIt : :WorkoutCommand
deactivate Parser

WerkIt -> Logic : execute()
activate Logic #LightSkyBlue

Logic -> UI : printNewWorkoutCreatedMessage(newWorkout)
activate UI #YellowGreen
return
deactivate UI

Logic -> Storage : writeNewWorkoutToFile(newWorkout)
activate Storage #IndianRed
return
deactivate Storage

Logic --> WerkIt
deactivate Logic

@enduml