@startuml
'https://plantuml.com/class-diagram
!include ../Style.puml

hide circle
skinparam classAttributeIconSize 0
skinparam classFontSize 16
title Class Diagram of `exercise` Command
Main -> WerkIt
WerkIt -> Parser
WerkIt -up-> UI
ExerciseList <-up- ExerciseCommand
"{abstract}\nCommand" <|- ExerciseCommand

class Main COLOR_MAIN {

}
Parser ..> "{abstract}\nCommand"
class WerkIt #Sandybrown {
+ startContinuousUserPrompt()
}

class "{abstract}\nCommand" #LightSkyBlue {
}



class ExerciseCommand #LightSkyBlue {
+ execute()
}

class UI #YellowGreen {
+ getUserInput()
}

class Parser #Gold {
+ parseUserInput(String userInput)
+ ExerciseCommand createExerciseCommand(String userInput)
}

class ExerciseList #LightSkyBlue {
+ exercisesList: ArrayList<String>
+ printExerciseList()
}

@enduml