@startuml
'https://plantuml.com/class-diagram'
hide circle

skinparam classAttributeIconSize 0
title Class Diagram of Plan Component

WerkIt -> Parser
WerkIt -> UI
WerkIt .r.> PlanCommand
Parser .d.> "{abstract}\nCommand"
"{abstract}\nCommand" <|-- PlanCommand
PlanCommand --> UI
PlanCommand -d-> FileManager
PlanCommand -r-> PlanList


class WerkIt {
+ startContinuousUserPrompt()
}

class PlanList {
+ createAndAddPlan(userArgument:String):Plan
+ listAllPlan():void
+ listPlanDetails(userArgument:String, ui:UI):void
+ deletePlan(userArgument:String):Plan
}

class FileManager {
+ writeNewPlanToFile(newPlan:Plan):void
+ rewriteAllPlansToFile(planList:PlanList):void
}

class "{abstract}\nCommand" {
}

class PlanCommand {
+ execute():void
}

class UI {
+ getUserInput()
+ printNewPlanCreatedMessage(newPlan:Plan):void
+ printDeletePlanMessage(deletedPlan:Plan):void
}

class Parser {
+ parseUserInput(userInput:String):Command
+ createPlanCommand(userInput:String):PlanCommand
}


@enduml