@startuml
'https://plantuml.com/class-diagram'

!include ../Style.puml

hide circle

skinparam classAttributeIconSize 0
title Class Diagram of Schedule Component

WerkIt -> Parser
WerkIt -> UI
Parser .r.> "{abstract}\nCommand"
"{abstract}\nCommand" <|-- ScheduleCommand
ScheduleCommand --> UI
ScheduleCommand -d-> FileManager
ScheduleCommand -r-> DayList
UI <. FileManager

class WerkIt COLOR_WERKIT {
+ startContinuousUserPrompt()
}

class DayList COLOR_LOGIC {
+ updateDay(String userArgument):Day
+ printSchedule()
+ clearDayPlan(String userArgument)
+ clearAllSchedule()
}

class FileManager COLOR_STORAGE {
+ addFileScheduleToList(DayList dayList, String[] scheduleFileDataLine):void
+ rewriteAllDaysScheduleToFile(DayList dayList):void
+ convertDayScheduleToFileDataFormat(Day day):String
}

class "{abstract}\nCommand" COLOR_LOGIC {
}

class ScheduleCommand COLOR_LOGIC {
+ execute():void
}



class UI COLOR_UI {
+ getUserInput()
+ printScheduleFileNotFoundMessage():void
+ printScheduleFileCreatedMessage():void
+ printNewScheduleCreatedMessage(Day newDay):void
+ printClearedScheduleMessage():void
}

class Parser COLOR_PARSER {
+ parseUserInput(String userInput):Command
+ createScheduleCommand(String userInput):ScheduleCommand
}


@enduml