@startuml
'https://plantuml.com/class-diagram
hide circle

skinparam classAttributeIconSize 0
skinparam classFontSize 16
title Class Diagram of `search` Command

Main -> WerkIt
WerkIt -> Parser
WerkIt --> UI
"{abstract}\nCommand" <|-- SearchCommand
ExerciseList <-left- SearchCommand
PlanList <- SearchCommand
WorkoutList <-u- SearchCommand
Parser ..> "{abstract}\nCommand"
skinparam classFontSize 16
class WerkIt #Sandybrown {
+ startContinuousUserPrompt()
}

class Main {

}

class SearchCommand #LightSkyBlue {
+ execute()
+ searchWorkout()
+ searchPlan()
+ searchWorkout()
+ searchExercise()
}

class "{abstract}\nCommand" #LightSkyBlue {
}

class UI #YellowGreen {
+ getUserInput()
}

class Parser #Gold {
+ parseUserInput(String userInput)
+ SearchCommand createSearchCommand(String userInput)
}

class ExerciseList #LightSkyBlue {
+ exercisesList: ArrayList<String>
}

class WorkoutList #LightSkyBlue {
+ workoutsDisplayList: ArrayList<String>
}

class PlanList #LightSkyBlue {
+ plansDisplayList: ArrayList<String>
}

@enduml