@startuml
'https://plantuml.com/class-diagram
hide circle

skinparam classAttributeIconSize 0
skinparam classFontSize 16
title Class Diagram of Workout-related Features

Parser .r.> "{abstract}\nCommand":creates >
"{abstract}\nCommand" <|- WorkoutCommand
WorkoutCommand -r-> WorkoutList
WorkoutCommand --> FileManager
WorkoutCommand --> UI
WorkoutCommand -u-> PlanList

class PlanList #LightSkyBlue {
+ deletePlanContainsDeletedWorkout(String deletedWorkoutDetail):void
+ updatePlanContainsUpdatedWorkout(String workoutToCheck, Workout updatedWorkout):void
}

class FileManager #IndianRed {
+ writeNewWorkoutToFile(Workout newWorkout):void
+ rewriteAllWorkoutsToFile(WorkoutList workoutList):void
+ rewriteAllPlansToFile(PlanList planList):void
}

class "{abstract}\nCommand" #LightSkyBlue {
}

class WorkoutCommand #LightSkyBlue {
+ execute():void
}

class WorkoutList #LightSkyBlue {
+ createAndAddWorkout(String userArgument):Workout
+ listAllWorkout():void
+ deleteWorkout(String userArgument):Workout
+ updateWorkout(String userArgument):Workout
}

class UI #YellowGreen{
+ printNewWorkoutCreatedMessage(Workout newWorkout):void
+ printDeleteWorkoutMessage(Workout deletedWorkout):void
+ printUpdateWorkoutMessage(Workout updatedWorkout):void
}

class Parser #Gold {
+ parseUserInput(String userInput):Command
+ createWorkoutCommand(String userInput):WorkoutCommand
}


@enduml