@startuml
'https://plantuml.com/sequence-diagram

hide footbox

actor user
participant ":DishManager" as dishmanager
participant "dishes:ArrayList<Dish>" as dishes
participant ":Dish" as dish


user -> dishmanager: deleteDish(index)
activate dishmanager

dishmanager -> dishmanager: throwIfIndexNotValid(index)
activate dishmanager

dishmanager -> dishes: size()
activate dishes
dishes --> dishmanager
deactivate dishes
group opt [index > size]
dishmanager --> user: IndexOutOfBoundsException
end

deactivate dishmanager

dishmanager -> dishes: remove(index)
activate dishes
dishes --> dishmanager
deactivate dishes
deactivate dish
destroy dish
@enduml