@startuml
'https://plantuml.com/sequence-diagram

autonumber
hide footbox

actor user
participant "__:DishManager__" as dishmanager
participant "__dishes:ArrayList<Dish>__" as dishes
participant "__:Dish__" as dish

activate dishmanager
activate dishes
activate dish

user -> dishmanager: addDish(dish)
dishmanager -> dishes: add(dish)
dishes --> dishmanager
dishmanager --> user

@enduml