@startuml
'https://plantuml.com/sequence-diagram

hide footbox

actor user
participant ":OrderController" as ordercontroller
participant ":OrderManager" as ordermanager
participant ":Order" as order

user -> ordercontroller: displayAllOrderPrice()
activate ordercontroller

ordercontroller -> ordermanager: getAllOrderValue()
activate ordermanager

ordermanager -> order : getTotalPrice()
activate order

order --> ordermanager : double
ordermanager --> ordercontroller : double
ordercontroller --> user

@enduml