@startuml
'https://plantuml.com/sequence-diagram

autonumber
hide footbox

actor user
participant "__:OrderController__" as ordercontroller
participant "__:OrderManager__" as ordermanager
participant "__:Order__" as order

activate ordercontroller
activate ordermanager
activate order
user -> ordercontroller: deleteOrder()

ordercontroller -> ordermanager: deleteOrder(int orderIdx)


ordermanager -> ordermanager: getOrderCount()

opt orderIdx >= number of existing orders
ordermanager --> ordercontroller : IndexOutOfBoundsException
end

deactivate order
destroy order

ordermanager --> ordercontroller
@enduml