@startuml
'https://plantuml.com/sequence-diagram

autonumber
hide footbox

actor user
participant ":StaffController" as staffcontroller
participant ":StaffManager" as staffmanager


user -> staffcontroller: deleteStaff()
activate staffcontroller

staffcontroller -> staffmanager: deleteByStaffId(int staffId)
activate staffmanager

staffmanager -> staffmanager : findStaff(int staffId)
activate staffmanager
staffmanager --> staffmanager
deactivate staffmanager

opt staff not found
staffmanager --> staffcontroller : IllegalArgumentException
end
@enduml