@startuml
'https://plantuml.com/sequence-diagram

hide footbox

actor user
participant ":StaffController" as staffcontroller
participant ":StaffManager" as staffmanager


user -> staffcontroller: findStaff()
activate staffcontroller

staffcontroller -> staffcontroller: isEmpty = checkStaffEmpty()
activate staffcontroller
staffcontroller --> staffcontroller
deactivate staffcontroller

alt staff records empty
staffcontroller --> user

else staff records not empty
staffcontroller -> staffmanager: staff  = findByStaffId(int staffId)
activate staffmanager
staffmanager --> staffcontroller

end
@enduml