@startuml
'https://plantuml.com/sequence-diagram

autonumber

Duke -> CommandParser: parse(check level 2)
CommandParser -> CheckRoomByLevelCommand: CheckRoomByLevelCommand()
Duke -> CheckRoomByLevelCommand: execute()
CheckRoomByLevelCommand -> CheckRoomByLevelCommand: isValidLevel = isValidLevel(2,roomList)
CheckRoomByLevelCommand -> CheckRoomByLevelCommand: printRoom(2,roomList)

@enduml