@startuml
'https://plantuml.com/class-diagram
hide empty members
skinparam classAttributeIconSize 0


Class UnitGood {
    +{static}restoreUnitGood(JSONObject jo):Order
    +serialize(): JSONObject
}
@enduml

