@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

autonumber

title Sequence Diagram of `plan /new` Command
hide footbox

participant "werkIt:WerkIt" AS WerkIt
participant "newCommand\n:PlanCommand" AS newCommand
participant "planList\n:PlanList" AS PlanList
participant "ui:UI" AS UI2
participant "fileManager:FileManager" as FileManager

activate WerkIt
ref over WerkIt
Obtain and parse user input.
end

WerkIt -> newCommand : execute()
activate newCommand
newCommand -> PlanList : createAndAddPlan(userArgument)
activate PlanList
ref over PlanList
Create new Plan
and add it to list.
end
newCommand <-- PlanList : newPlan:Plan
deactivate PlanList

newCommand -> UI2 : printNewPlanCreatedMessage(newPlan)
activate UI2
newCommand <-- UI2
deactivate UI2

newCommand -> FileManager : writeNewPlanToFile(newPlan)
activate FileManager
ref over FileManager
Write new Plan data
into file on user's system.
end
newCommand <-- FileManager
deactivate FileManager

WerkIt <-- newCommand
deactivate newCommand

destroy newCommand
@enduml