@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

autonumber

title Sequence Diagram of `plan /new` Command
hide footbox

participant "werkIt:WerkIt" AS WerkIt COLOR_WERKIT
participant "newCommand\n:PlanCommand" AS newCommand COLOR_LOGIC
participant "planList\n:PlanList" AS PlanList COLOR_LOGIC
participant "ui:UI" AS UI2 COLOR_UI
participant "fileManager:FileManager" as FileManager COLOR_STORAGE

activate WerkIt COLOR_WERKIT
ref over WerkIt
Obtain and parse user input.
end

WerkIt -> newCommand : execute()
activate newCommand COLOR_LOGIC
newCommand -> PlanList : createAndAddPlan(userArgument)
activate PlanList COLOR_LOGIC
ref over PlanList
Create new Plan
and add it to list.
end
newCommand <-- PlanList : newPlan:Plan
deactivate PlanList

newCommand -> UI2 : printNewPlanCreatedMessage(newPlan)
activate UI2 COLOR_UI
newCommand <-- UI2
deactivate UI2

newCommand -> FileManager : writeNewPlanToFile(newPlan)
activate FileManager COLOR_STORAGE
ref over FileManager
Write new Plan data
into file on user's system.
end
newCommand <-- FileManager
deactivate FileManager

WerkIt <-- newCommand
deactivate newCommand

destroy newCommand
@enduml