@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

autonumber

title Sequence Diagram of `plan /delete` Command
hide footbox

participant "werkIt:WerkIt" AS WerkIt COLOR_WERKIT
participant "newCommand\n:PlanCommand" AS deleteCommand COLOR_LOGIC
participant "planList\n:PlanList" AS PlanList COLOR_LOGIC
participant "ui:UI" AS UI2 COLOR_UI
participant "fileManager\n:FileManager" as FileManager COLOR_STORAGE

activate WerkIt COLOR_WERKIT
ref over WerkIt
Obtain and parse user input.
end

WerkIt -> deleteCommand : execute()
activate deleteCommand COLOR_LOGIC
deleteCommand -> PlanList : deletePlan(userArguments)
activate PlanList COLOR_LOGIC
ref over PlanList
Delete plan specified by user.
end
deleteCommand <-- PlanList : deletedPlan : Plan
deactivate PlanList

deleteCommand -> UI2 : printDeletePlanMessage(deletedPlan)
activate UI2 COLOR_UI
deleteCommand <-- UI2
deactivate UI2

deleteCommand -> FileManager : rewriteAllPlansToFile(planList))
activate FileManager COLOR_STORAGE
ref over FileManager
Rewrite modified planList
data into file on user's system
end
deleteCommand <-- FileManager
deactivate FileManager

WerkIt <-- deleteCommand
deactivate deleteCommand

destroy deleteCommand
@enduml