@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

autonumber

title Sequence Diagram of `plan /list` Command
hide footbox

participant "werkIt:WerkIt" AS WerkIt #Sandybrown
participant "newCommand\n:PlanCommand" AS newCommand #LightSkyBlue
participant "planList\n:PlanList" AS PlanList #LightSkyBlue

activate WerkIt #Sandybrown
ref over WerkIt
Obtain and parse user input.
end

WerkIt -> newCommand : execute()
activate newCommand #LightSkyBlue
newCommand -> PlanList : listAllPlan()
activate PlanList #LightSkyBlue
opt application plan list is empty
newCommand <-- PlanList : No plan created yet message
end
loop all plans in plan list
newCommand <-- PlanList : Show name of plans
end
newCommand <-- PlanList
deactivate PlanList

WerkIt <-- newCommand
deactivate newCommand

destroy newCommand
@enduml