@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

autonumber

title Sequence Diagram of `plan /list` Command
hide footbox

participant "werkIt:WerkIt" AS WerkIt
participant "newCommand\n:PlanCommand" AS newCommand
participant "planList\n:PlanList" AS PlanList

activate WerkIt
ref over WerkIt
Obtain and parse user input.
end

WerkIt -> newCommand : execute()
activate newCommand
newCommand -> PlanList : listAllPlan()
activate PlanList
opt application plan list is empty
newCommand <-- PlanList : No plan created yet message
end
loop all plans in plan list
newCommand <-- PlanList : Show name of plans
end
newCommand <-- PlanList
deactivate PlanList

WerkIt <-- newCommand
deactivate newCommand

destroy newCommand
@enduml