@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

autonumber

title Sequence Diagram of `workout /new` Command
hide footbox

participant "werkIt:WerkIt" AS WerkIt
participant "newCommand\n:WorkoutCommand" AS newCommand
participant "ui:UI" as UI
participant "workoutList\n:WorkoutList" AS WorkoutList
participant "fileManager:FileManager" as FileManager

activate WerkIt

ref over WerkIt
Obtain and parse user input.
end

WerkIt -> newCommand : execute()
activate newCommand
newCommand -> WorkoutList : createAndAddWorkout(userArguments)
activate WorkoutList
ref over WorkoutList
Create new Workout
and add it to list.
end
newCommand <-- WorkoutList : "newWorkout:Workout"
deactivate WorkoutList

newCommand -> UI : printNewWorkoutCreatedMessage(newWorkout)
activate UI
return

newCommand -> FileManager : writeNewWorkoutToFile(newWorkout)
activate FileManager
ref over FileManager
Write new Workout data
into file on user's system.
end
newCommand <-- FileManager
deactivate FileManager

WerkIt <-- newCommand
deactivate newCommand

destroy newCommand
@enduml