@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

autonumber

title Sequence Diagram of `workout /delete` Command
hide footbox

participant "werkIt:WerkIt" AS WerkIt
participant "deleteCommand\n:WorkoutCommand" AS deleteCommand
participant "workoutList\n:WorkoutList" AS WorkoutList
participant "ui:UI" AS UI2
participant "fileManager\n:FileManager" as FileManager

activate WerkIt
ref over WerkIt
Obtain and parse user input.
end

WerkIt -> deleteCommand : execute()
activate deleteCommand
deleteCommand -> WorkoutList : deleteWorkout(userArguments)
activate WorkoutList
ref over WorkoutList
Delete workout specified by user.
end
deleteCommand <-- WorkoutList : deletedWorkout:Workout
deactivate WorkoutList

deleteCommand -> UI2 : printDeleteWorkoutMessage(deletedWorkout)
activate UI2
deleteCommand <-- UI2
deactivate UI2

deleteCommand -> WorkoutList : deletePlanContainsDeletedWorkout(deletedWorkout.toString(), planList)
activate WorkoutList
deleteCommand <-- WorkoutList
deactivate WorkoutList

deleteCommand -> FileManager : rewriteAllWorkoutsToFile(workoutList)
activate FileManager
ref over FileManager
Rewrite modified workoutList
data into file on user's system
end
deleteCommand <-- FileManager
deactivate FileManager

deleteCommand -> FileManager : rewriteAllPlansToFile(planList)
activate FileManager
ref over FileManager
Rewrite modified planList
data into file on user's system
end
deleteCommand <-- FileManager
deactivate FileManager

WerkIt <-- deleteCommand
deactivate deleteCommand

destroy deleteCommand
@enduml