@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

autonumber 2.1

title Sequence Diagram of `WorkoutList#deleteWorkout()`
hide footbox

participant "workoutList\n:WorkoutList" AS wl #LightSkyBlue

activate wl #LightSkyBlue
wl -> ":Integer" :parseInt(userArgument)
activate ":Integer"
return indextoDelete:int
deactivate ":Integer"

wl -> wl :getWorkoutFromIndexNum(indexToDelete)
activate wl #LightSkyBlue
return deletedWorkout:Workout

wl -> "workoutsDisplayList:\nArrayList<String>" :remove(indexToDelete - 1)
activate "workoutsDisplayList:\nArrayList<String>"
return
deactivate "workoutsDisplayList:\nArrayList<String>"

wl -> "workoutsHashMapList:\nHashMap" :remove(deletedWorkout)
activate "workoutsHashMapList:\nHashMap"
return
deactivate "workoutsHashMapList:\nHashMap"

@enduml