@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

autonumber

title Sequence Diagram of `workout /delete` Command
hide footbox

participant "werkIt:WerkIt" AS WerkIt #Sandybrown
participant "deleteCommand\n:WorkoutCommand" AS deleteCommand #LightSkyBlue
participant "workoutList\n:WorkoutList" AS WorkoutList #LightSkyBlue
participant "ui:UI" AS UI2 #YellowGreen
participant "planList\n:PlanList" AS PlanList #LightSkyBlue
participant "fileManager\n:FileManager" as FileManager #IndianRed

activate WerkIt #Sandybrown
ref over WerkIt
Obtain and parse user input.
end

WerkIt -> deleteCommand : execute()
activate deleteCommand #LightSkyBlue
deleteCommand -> WorkoutList : deleteWorkout(userArguments)
activate WorkoutList #LightSkyBlue
ref over WorkoutList
Delete workout specified by user.
end
deleteCommand <-- WorkoutList : deletedWorkout:Workout
deactivate WorkoutList

deleteCommand -> UI2 : printDeleteWorkoutMessage(deletedWorkout)
activate UI2 #YellowGreen
deleteCommand <-- UI2
deactivate UI2

deleteCommand -> PlanList : deletePlanContainsDeletedWorkout(deletedWorkout.toString())
activate PlanList #LightSkyBlue
deleteCommand <-- PlanList
deactivate PlanList

deleteCommand -> FileManager : rewriteAllWorkoutsToFile(workoutList)
activate FileManager #IndianRed
ref over FileManager
Rewrite modified workoutList
data into file on user's system
end
deleteCommand <-- FileManager
deactivate FileManager

deleteCommand -> FileManager : rewriteAllPlansToFile(planList)
activate FileManager #IndianRed
ref over FileManager
Rewrite modified planList
data into file on user's system
end
deleteCommand <-- FileManager
deactivate FileManager

WerkIt <-- deleteCommand
deactivate deleteCommand

destroy deleteCommand
@enduml