@startuml
!include <office/Concepts/documents>
!include <office/Users/user>

rectangle "<$user>\nUser" as User #Pink
rectangle "<$documents>\nFiles" as Files #Snow

title Architecture Diagram for WerkIt!
rectangle {
rectangle UI #YellowGreen
rectangle Command #LightSkyBlue
rectangle Parser #Gold
rectangle WerkIt #Sandybrown
rectangle Main #Cornsilk
rectangle Storage #IndianRed
rectangle LogHandler #Orchid
}

UI<.-up-User
Main-up->WerkIt
WerkIt-up->Parser
Parser-up.>Command
Command-right->Storage
WerkIt-right->Storage
Main-right->LogHandler
WerkIt-left->UI
Storage-right.>Files
Files-left.>Storage

@enduml