@startuml
'https://plantuml.com/sequence-diagram

autonumber

Spendvelope -> TextUi: getUserCommand()
loop shouldIgnore
    TextUi -> TextUi: shouldIgnore()
end

TextUi -> TextUi: showToUser()
TextUi -> Spendvelope: fullInputLine

@enduml