@startuml
'https://plantuml.com/sequence-diagram

hide footbox
autonumber
autoactivate on
loop
|||
ref over Spendvelope, TextUi: getUserInput
Spendvelope -> Parser: parseCommand(fullUserInput)
Parser -> Command**:
Parser <-- Command
Spendvelope <-- Parser: command
Spendvelope -> Spendvelope: executeCommand(command)
Spendvelope -> Command: execute()
Command -> CommandResult**:
Command <-- CommandResult:result
Spendvelope <-- Command: result
destroy Command
Spendvelope <-- Spendvelope: result
Spendvelope -> TextUi: showResultToUser(result)
end

@enduml