@startuml
'https://plantuml.com/sequence-diagram
!include ../Style.puml

autonumber 7.1

title Sequence Diagram of `PlanList#createAndAddPlan()`

participant "planList\n:PlanList" AS pl
participant "workoutList\n:WorkoutList" AS wl

activate pl
group sd Write new Plan data into file on user's system.

ref over pl
Parse the user input to obtain the plan name
and the workout index numbers separated by comma.
(Method calls not shown)
end

pl -> pl : checkPlanNameValidity(userPlanNameInput, className)
activate pl
return


ref over pl
Obtain number of workouts to be added into
the new plan (split string by comma).
(Method calls not shown)
end

pl -> pl : checkMinMaxNumberOfWorkouts(numberOfWorkoutsInAPlan, className)
activate pl
return

create "workoutsToAddInAPlanList:ArrayList<Workout>" AS wtoadd
pl -> wtoadd : new
activate wtoadd
return

loop until all workouts to be added in a plan is added

ref over pl
Get each individual workout index numbers from user
input string and convert them into an Integer.
(Method calls not shown)
end

pl -> pl : checkWorkoutNumberWithinRange(workoutIndexNumberInteger, className)
activate pl
return

pl -> wtoadd : add(workoutToAddObject)
activate wtoadd
return
end

pl -> pl : checkPlanWithSameWorkoutSequence(workoutsToAddInAPlanList, className)
activate pl
return

create "newPlan:Plan" AS newPlan
pl -> newPlan : new Plan(userPlanNameInput, workoutsToAddInAPlanList)
activate newPlan
return newPlan:Plan

pl -> "plansHashMapList\n:HashMap" : put(newPlanKey, newPlan)
activate "plansHashMapList\n:HashMap"
return

pl -> "plansDisplayList\n:ArrayList<String>" : add(newPlanKey)
activate "plansDisplayList\n:ArrayList<String>"
return

end
@enduml