@startuml
'https://plantuml.com/sequence-diagram
!include ../Style.puml

autonumber

title Sequence Diagram of `search /plan` Command

actor   User
participant "werkIt:WerkIt" AS WerkIt
participant "ui:UI" AS UI1
participant "parser:Parser" AS Parser
participant "newCommand\n:SearchCommand" AS newCommand
participant "planList\n:PlanList" AS PlanList

activate WerkIt
WerkIt -> UI1 : getUserInput()
activate UI1
User -> UI1 : `search /plan` command
WerkIt <-- UI1 : userInputTrimmed:String
deactivate UI1

WerkIt -> Parser : parseUserInput(userInput)
activate Parser
WerkIt <-- Parser : :Command
deactivate Parser

WerkIt -> newCommand : execute()
activate newCommand
newCommand -> PlanList : getPlansDisplayList()
activate PlanList

newCommand <-- PlanList : "planList:ArrayList<String>"
deactivate PlanList

newCommand -> newCommand : searchPlan()
User <-- newCommand : search outcome

deactivate newCommand

destroy newCommand
@enduml