@startuml
'https://plantuml.com/sequence-diagram
!include ../Style.puml

autonumber

title Sequence Diagram of `schedule /list` Command

actor   User
participant "werkIt:WerkIt" AS WerkIt
participant "ui:UI" AS UI1
participant "parser:Parser" AS Parser
participant "newCommand\n:ScheduleCommand" AS newCommand
participant "dayList\n:DayList" AS DayList


activate WerkIt
WerkIt -> UI1 : getUserInput()
activate UI1
User -> UI1 : `schedule /list` command
WerkIt <-- UI1 : userInputTrimmed:String
deactivate UI1

WerkIt -> Parser : parseUserInput(userInput)
activate Parser
WerkIt <-- Parser : :Command
deactivate Parser

WerkIt -> newCommand : execute()
activate newCommand

newCommand -> DayList : printSchedule()
activate DayList
loop 7 times

DayList -> DayList : padWithSpaces(planForDay)
activate DayList
return planForDayWithPadding:string

end
User <-- DayList : Display plans scheduled for the week
return
destroy newCommand
@enduml