@startuml
'https://plantuml.com/sequence-diagram

skinparam shadowing false
participant ":ModHappyParser" as ModHappyParser
participant "<<class>>\nEditParser" as EditParser
participant ":EditTaskParser" as EditTaskParser
participant ":EditCommand" as EditCommand
participant ":ModuleList" as ModuleList
participant ":Module" as Module
participant ":TaskList" as TaskList
participant ":Task" as Task
hide footbox

note right of ModHappyParser
Some methods are omitted from this diagram.
end note

[->ModHappyParser:parseCommand(userInput)
activate ModHappyParser

ModHappyParser -> EditParser: getParser()
activate EditParser
return new EditTaskParser()
create EditTaskParser
ModHappyParser -> EditTaskParser: parseCommand(arguments)
activate EditTaskParser
create EditCommand
EditTaskParser -> EditCommand: EditCommand(arguments)
activate EditCommand
return
return
return

destroy EditTaskParser

[->EditCommand:execute(moduleList, configuration)
activate EditCommand
ref over EditCommand, ModuleList: Get Module
EditCommand -> EditCommand: editTaskFromModule(targetModule)
activate EditCommand
ref over EditCommand, TaskList: Get Task
EditCommand -> Task: setTaskDescription(description)
activate Task
return
deactivate Task
return CommandResult(result)
deactivate EditCommand

destroy EditCommand


@enduml