@startuml
hide footbox
actor user
participant ":Command" as Main
participant ":Parser" as Parser
participant ":AddLessonCommand" as AddCommand

activate Main
user -> Main : "add_lesson..."
create Parser
Main -> Parser : Parser("add_lesson ...")
activate Parser
Main <-- Parser : parser:Parser
deactivate Parser

Main --> Parser : parseCommand()
activate Parser

Parser -> Parser : prepareAdd()
activate Parser

create AddCommand
Parser -> AddCommand
activate AddCommand
Parser <-- AddCommand
deactivate AddCommand

Parser --> Parser : :Command
deactivate Parser
Main <-- Parser : parsedCommand:Command
deactivate Parser
destroy Parser

Main -> AddCommand : execute(masterTimetable:MasterTimetable)
activate AddCommand
Main <-- AddCommand : feedback:String
deactivate AddCommand

destroy AddCommand
@enduml