@startuml
hide footbox


create ":Ui"

create ":AddMeetingCommand"
":Ui" -> ":AddMeetingCommand" ++: AddMeetingCommand("meeting1","Thursday",1230,1330,"online")
":AddMeetingCommand" --> ":Ui" -- :
":Ui" -> ":AddMeetingCommand" ++: execute(masterTimetable)
":AddMeetingCommand" -> ":Meeting" ++ : new()
":Meeting" --> ":AddMeetingCommand" --: meeting:Meeting

":AddMeetingCommand" -> ":MasterTimetable" ++: addMeetingToEveryoneTimetable(meeting:Meeting)
":MasterTimetable" -> ":Timetable" ++ : add(meeting:Meeting)
":Timetable" -> ":Timetable"++: addMeetingConfirmation(meeting:Meeting)
":Timetable" --> ":MasterTimetable" --: addMeetingConfirmation:String
":MasterTimetable" --> ":AddMeetingCommand" -- :
":AddMeetingCommand" --> ":Ui" --:

destroy ":AddMeetingCommand"


@enduml