@startuml
hide footbox

participant "Unspecified" as none
participant ":AddUserCommand" as Command
participant ":MasterTimetable" as Master
participant ":Timetable" as Timetable

create Command
none -> Command : AddUserCommand("john")
activate Command
none <-- Command :
deactivate Command

none -> Command : execute(masterTimetable)
activate Command
create Timetable
Command -> Timetable : Timetable("john")
activate Timetable
Command <-- Timetable : timetable :Timetable
deactivate Timetable

Command ->  Master : addTimetable(timetable)
activate Master
Command <-- Master
deactivate Master

Command -> Command : addConfirmation("john")
activate Command
Command --> Command : :String
deactivate Command

none <-- Command : :String
deactivate Command
destroy Command

@enduml