@startuml

hide footbox
skinparam guillemet false
skinparam sequenceStereotypeFontColor red
skinparam sequenceStereotypeFontStyle bold

participant ":InvMgr" as InvMgr
participant "storage:Storage" as Storage
participant "ui:Ui" as Ui
participant "itemList:ItemList" as ItemList
participant ":Parser" as Parser <<class>>
participant ":Command" as Command

-> InvMgr: main()
activate InvMgr
    create Ui
    InvMgr -> Ui: Ui()
    activate Ui
    return

    create Storage
    InvMgr -> Storage: Storage(filePath)
    activate Storage
    return

    InvMgr -> Storage: load()
    activate Storage
    return list: ArrayList<Item>

    create ItemList
    InvMgr -> ItemList: ItemList(list)
    activate ItemList
    return

    loop until ExitCommand
        InvMgr -> Ui: getRawUserInput()
        activate Ui
        return command: String

        InvMgr -> Parser: parse(command)
        activate Parser
        return inputCommand: Command

        InvMgr -> Command: execute(itemList, ui)
        activate Command
        return

        InvMgr -> Storage: save(itemList)
        activate Storage
        return
    end
deactivate InvMgr

@enduml
