@startuml
!include style.puml

box
Actor User USER_COLOR
Participant Main #grey
Participant "Commands\nComponent" as Commands COMMAND_COLOR
Participant "Parser\nComponent" as Parser LOGIC_COLOR
Participant "Family\nComponent" as Family MODEL_COLOR
Participant "Money\nComponent" as Money MONEY_COLOR
Participant "UI\nComponent" as UI UI_COLOR
Participant "Storage\nComponent" as Storage STORAGE_COLOR
end box

User -> Main : "add /g 2 /n Alice"

activate Main
Main -> Commands : getCommand("add /g 2 /n Alice")

activate Commands
Commands -> Parser : parseCommandType(\n"add /g 2 /n Alice")

activate Parser
Parser --> Commands
deactivate Parser

Commands --> Main : :AddPersonCommand
deactivate Commands

Main -> UI : printHoriLine()
activate UI
UI --> Main
deactivate UI

Main -> Commands : execute()
activate Commands

Commands -> Parser : parseName(\n"add /g 2 /n Alice")
activate Parser
Parser --> Commands : "Alice":String
deactivate Parser

Commands -> Parser : parseGroupIndex(\n"add /g 2 /n Alice")
activate Parser
Parser --> Commands : "2":String
deactivate Parser
Commands -> Parser : getValidGroupIndex(\n"2":String)
activate Parser
Parser --> Commands : 2:int
deactivate Parser

Commands -> Family : addPerson(2:int, "Alice":String)
activate Family

Family -> Family : addPerson("Alice")
activate Family

Family -> Money : new IncomeList()
activate Money
Money --> Family
deactivate Money

Family -> Money : new ExpenseList()
activate Money
Money --> Family
deactivate Money

Family --> Family
deactivate Family

Family --> Commands
deactivate Family

Main -> UI : printHoriLine()
activate UI
UI --> Main
deactivate UI

Commands -> Storage : saveData()
activate Storage
Storage --> Commands
deactivate Storage

Commands --> Main
deactivate Commands

Main --> User

@enduml

