@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Commands COMMAND_COLOR
    Class Storage STORAGE_COLOR
    Class Family MODEL_COLOR
    Class MoneyList MONEY_COLOR
    Class Main #grey
    Class Parser LOGIC_COLOR
}

Class "<$user>\nUser" as User MODEL_COLOR_T2
Class "<$documents>\nSaved Data" as File STORAGE_COLOR_T3

Main -right[#grey]->UI
Main -down[#grey]->Family
Main -right[#grey]->Commands
Main -down[#grey]->Storage

Commands -up[COMMAND_COLOR]->UI
Commands -left[COMMAND_COLOR]->Family
Commands -down[COMMAND_COLOR].>Storage
Commands -down[COMMAND_COLOR].>Parser

Family -down[MODEL_COLOR]->MoneyList

Storage -left[STORAGE_COLOR]>Family
Storage .down[STORAGE_COLOR].>File

User ..> Main
@enduml

