@startuml
!include style.puml

box
Actor User USER_COLOR
Participant Main #grey
Participant Commands COMMAND_COLOR
Participant "Parser" as Parser LOGIC_COLOR
Participant Family MODEL_COLOR
Participant Money MONEY_COLOR
Participant UI UI_COLOR
Participant Storage STORAGE_COLOR
end box

User -> Main : "add /g 2 /n Alice"

activate Main
Main -> Commands : getCommand("add /g 2 /n Alice")

activate Commands
Commands -> Parser : parseKeyword(\n"add /g 2 /n Alice")

activate Parser
Parser --> Commands
deactivate Parser

Commands --> Main : :AddPersonCommand
deactivate Commands

Main -> UI : //print start execution line//
activate UI
UI --> Main
deactivate UI

Main -> Commands : execute()
activate Commands

Commands -> Parser : //parse various details//
activate Parser
Parser --> Commands
deactivate Parser

Commands -> Family : addPerson(2:int, "Alice":String)
activate Family

Family -> Family : addPerson("Alice")
activate Family

Family -> Money : IncomeList()
activate Money
Money --> Family
deactivate Money

Family -> Money : ExpenseList()
activate Money
Money --> Family
deactivate Money

Family --> Family
deactivate Family

Family --> Commands
deactivate Family

Main -> UI : //print end execution line//
activate UI
UI --> Main
deactivate UI

Commands -> Storage : saveData()
activate Storage
Storage --> Commands
deactivate Storage

Commands --> Main
deactivate Commands

Main --> User

@enduml

