@startuml
'https://plantuml.com/sequence-diagram
hide footbox
skinparam guillemet false
skinparam sequenceStereotypeFontColor red
skinparam sequenceStereotypeFontStyle bold

Participant ":InvMgr" as invmgr
Participant "InputParser" as parser <<class>>
Participant "CancelFutureBorrowingsParser" as cancelparser <<class>>
Participant ":CancelFutureBorrowingsCommand" as cancelcmd
Participant "records:ArrayList<BorrowRecord>" as rmvrcd
Participant "items:ArrayList<Item>" as itmlst
Participant "item:Item" as itm
Participant "itemRecords:ArrayList<borrowRecord>" as itmrcd
Participant "ui:Ui" as ui

activate invmgr

-> invmgr
invmgr -> parser:parse("cancel p/ABC i/1")
activate parser

parser -> cancelparser:CancelFutureBorrowingsParser().parse()
activate cancelparser
create cancelcmd
cancelparser -> cancelcmd:CancelFutureBorrowingsCommand(name, index)
activate cancelcmd
return
return
return inputCommand:CancelFutureBorrowingsCommand

invmgr -> cancelcmd:execute(itemList: ItemList, ui: Ui)

activate cancelcmd
cancelcmd -> cancelcmd:getBorrowRecords(borrowerName, itemList)
activate cancelcmd
return records

cancelcmd -> cancelcmd:getItems(borrowerName, itemList)
activate cancelcmd
return items

cancelcmd -> rmvrcd:get(index)
activate rmvrcd
return removeRecord

cancelcmd -> itmlst:get(index)
activate itmlst
return item

cancelcmd -> itm:getBorrowRecords()
activate itm
return itemRecords

cancelcmd -> itmrcd:remove(removeRecord)
activate itmrcd
return

cancelcmd -> ui:showMessages()
activate ui
return
return

@enduml