@startuml
actor user

user -> ":Ui" ++ : "clear all"
create ":Parser"
":Ui" -> ":Parser" ++: new Parser("clear all")
":Parser" --> ":Ui" --: parser:Parser
":Ui" -> ":Parser" ++: parseCommand("clear all")
create ":ClearCommand"
":Parser" -> ":ClearCommand" ++: new ClearCommand()
":ClearCommand" --> ":Parser" --: clearCommand:ClearCommand
":Parser" --> ":Ui" --: clearCommand:ClearCommand
":Ui" -> ":ClearCommand" ++: execute(masterTimetable)
":ClearCommand" -> ":ClearCommand": clearAll(masterTimetable)
loop for each entry in MasterTimetable
":ClearCommand" -> ":MasterTimetable" ++: getByIndex(0)
":MasterTimetable" --> ":ClearCommand" -- : timetable: Timetable
loop for each entry in timetable
":ClearCommand" -> ":ClearCommand": clearTimetable(timetable)
":ClearCommand" -> ":MasterTimetable" : removeByIndex(0)
":MasterTimetable" --> ":ClearCommand" :
deactivate ":ClearCommand"
end
end

":ClearCommand" --> ":Ui" --: 
":Ui" --> user
destroy ":ClearCommand"
destroy ":Parser"
destroy ":MasterTimetable"
destroy ":Ui"
@enduml