@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide empty members

abstract class CommandParser {
matches : HashMap<String, String>
userInput : String
warehouse : Warehouse
# {abstract} init_extract_params() : void
# {abstract} extract_params() : void
+parse(String userInput) : void
}

AddParser -up-|> CommandParser
ViewParser -up-|> CommandParser
RemoveParser -up-|> CommandParser
ListParser -up-|> CommandParser
FindParser -up-|> CommandParser
HelpParser -up-|> CommandParser
FulfillParser -up-|> CommandParser

CommandParser -> Warehouse


@enduml