@startuml

abstract Command {
 -isExit:boolean
 +execute(itemList:ItemList, ui:Ui):void
 +isExit():boolean {abstract}
}

class AddCommand {
 -itemToAdd:Item
 +execute(itemList:ItemList, ui:Ui):void
}

class DescCommand {
 -index:int
 +execute(itemList:ItemList, ui:Ui):void
}

class ListCommand {
 +execute(itemList:ItemList, ui:Ui):void
}

class DeleteCommand {
 -index:int
 +execute(itemList:ItemList, ui:Ui):void
}

class HelpCommand {
 +execute(itemList:ItemList, ui:Ui):void
}


class ExitCommand {
 +execute(itemList:ItemList, ui:Ui):void
 +isExit():boolean
}

Command <|-- AddCommand
Command <|-- DescCommand
Command <|-- ListCommand
Command <|-- DeleteCommand
Command <|-- HelpCommand
Command <|-- ExitCommand

@enduml