@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

Box " "#WHITE
    participant Main LOGIC_COLOR_T1
    participant ":CommandFactory" as CommandFactory LOGIC_COLOR_T2
    participant ":Parser" as Parser LOGIC_COLOR_T3
    participant ":Command" as Command LOGIC_COLOR_T4

end Box

-> Main: userInput
activate Main
Main -> CommandFactory: getCommand(userInput, PersonList)
activate CommandFactory
CommandFactory -> Parser: parseKeywords(userInput)
activate Parser
Parser --> CommandFactory: return
deactivate Parser
CommandFactory --> Main: return
deactivate CommandFactory
Main -> Command: execute()
activate Command
@enduml
