@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

Box " "#WHITE
    participant Main LOGIC_COLOR_T1
    participant ":CommandFactory" as CommandFactory LOGIC_COLOR_T2
    participant ":Parser" as Parser LOGIC_COLOR_T3
    participant ":XYZCommand" as XYZCommand LOGIC_COLOR_T4
end Box

-> Main: userInput
activate Main
Main -> CommandFactory: getCommand(userInput, family)
activate CommandFactory
CommandFactory -> Parser: parseCommandTypes(userInput)
activate Parser
Parser --> CommandFactory: return
deactivate Parser
create XYZCommand
CommandFactory --> XYZCommand
activate XYZCommand
XYZCommand --> CommandFactory: :XYZCommand
deactivate XYZCommand
CommandFactory --> Main: return
deactivate CommandFactory
Main -> XYZCommand: execute()
activate XYZCommand
@enduml
