@startuml
'https://plantuml.com/class-diagram
skinparam groupInheritance 2

!include style.puml

Package Command as C {
    class XYZCommand COMMAND_COLOR_T1
    abstract class Command COMMAND_COLOR_T1
    class CommandFactory COMMAND_COLOR

}

XYZCommand -[COMMAND_COLOR_T1]-|> Command
CommandFactory -[COMMAND_COLOR]->"0..1" Command : Returns >

@enduml