@startuml
'https://plantuml.com/sequence-diagram


class Commands {
    + addGood(id, name, qty)
    + removeGood(id, qty, userOrderlines)
    + listGoods(userOrderlines)
    + viewGood(id, userOrderlines)
    + totalGoods((userOrderlines)
    + checkPlural(numberOfGoods)
    - remove(id, qty, userOrderlines)
}

@enduml