@startuml
!include style.puml

box
    participant ":IncomeList" as Ilist MONEY_COLOR
    participant "item:Income" as Inc MONEY_COLOR_T1
    participant ":ArrayList<Income>" as Alist MONEY_COLOR_T2
end box

participant ":System" as System SYSTEM_COLOR

[-> Ilist: editIncome(1:Integer, 1:Integer, "Bills":String,\n null ,null)
Ilist -> Alist: get(0:Integer)
activate Ilist
activate Alist
Alist --> Ilist : item:Income
deactivate Alist
Ilist -> Ilist: isDescEdited(item:Income, "Bills":Integer)
activate Ilist
Ilist -> Inc: getDescription()
activate Inc
Inc --> Ilist: description:String
deactivate Inc

opt OPT_COLOR description != null && !Description.equals("Bills":String)
    Ilist -> Inc: setDescription("Bills":String)
    activate Inc
    Inc --> Ilist
    deactivate Inc
end opt

Ilist --> Ilist: isDescEdited:Boolean
note right: True returned if opt taken,\n False otherwise.
deactivate Ilist
deactivate Alist

Ilist -> Ilist: isPermEdited(item:Income, null)
activate Ilist
Ilist -> Inc: isPermanent()
activate Inc
Inc --> Ilist: isPermanent:Boolean
deactivate Inc

opt OPT_COLOR isPermanent != null && !isPermanent.equals(null)
    Ilist -> Inc: setPermanent(null)
    activate Inc
    Inc --> Ilist:
    deactivate Inc
end opt

Ilist --> Ilist: isPermEdited:Boolean
note right: True returned if opt taken,\n False otherwise.
deactivate Ilist
deactivate Alist

Ilist -> Ilist: isAmountEdited(item:Income, null)
activate Ilist
Ilist -> Inc: getAmount()
activate Inc
Inc --> Ilist: amount:Double
deactivate Inc

opt OPT_COLOR Amount != null && !Amount.equals(null)
    Ilist -> Inc: setAmount(null)
    activate Inc
    Inc --> Ilist
    deactivate Inc
end opt

Ilist --> Ilist: isAmountEdited:Boolean
note right: True returned if opt taken,\n False otherwise.
deactivate Ilist
deactivate Alist

Ilist -> Ilist: printEditMsg(isDescEdited:Boolean, isPermEdited:Boolean, \nisAmountEdited:Boolean)
activate Ilist
alt OPT_COLOR isDescEdited || isAmountEdited || isPermEdited
    Ilist -> System:println("Your Income have been edited")
    activate System
    Ilist <-- System
    deactivate System
    Ilist -> System:println(item:Income)
    activate System
    Ilist <-- System
    deactivate System
else else
    Ilist -> System:println("No changes have been made")
    activate System
    Ilist <-- System
    deactivate System
end alt

Ilist -->[
deactivate Ilist

@enduml
