@startuml
'https://plantuml.com/class-diagram

class HalpmiException {
    +HalpmiException(String)
    +toString() : String
}
class DuplicateEntryException {
    +DuplicateEntryException(String)
    +toString() : String
 }

class NotFoundException {
    +DuplicateEntryException(String)
    +toString() : String
}
DuplicateEntryException --|> Exception
HalpmiException --|> Exception
NotFoundException --|> Exception
@enduml