@startuml
!include style.puml
skinparam arrowColor #BLACK
skinparam noteTextAlignment left

Title: Family component command handling (Step 1)

participant ":XYZCommand" as Command COMMAND_COLOR

box
participant ":Family" as Family MODEL_COLOR
participant "parents:PersonList" as Parents MODEL_COLOR_T3
participant ":Person" as Person MODEL_COLOR_T2
end box

participant ":System" as System SYSTEM_COLOR
participant ":MoneyList" as Money MONEY_COLOR

-> Command: add /n Alice /g 1
activate Command
Command -> Family: addPerson()
activate Family
Family -> Family: getList()
activate Family
Family --> Family: :PersonList
deactivate Family
Family -> Parents: addPerson()
activate Parents
create Person
Parents -> Person: Person()
activate Person
create Money
Person -> Money: MoneyList()
activate Money
Person <-- Money
deactivate Money
Parents <-- Person
deactivate Person
Family <-- Parents
deactivate Parents
opt OPT_COLOR Not Silent
    Family -> Family: getGenerationName()
    activate Family
    Family --> Family: generation:String
    deactivate Family
    Family -> Family: printPersonAdded()
    activate Family
    Family -> System: println()
    activate System
    Family <-- System
    Family --> Family
    deactivate System
    deactivate Family
end opt
Command <-- Family
deactivate Family
<-- Command
deactivate Command

@enduml
