@startuml
!include style.puml
skinparam arrowColor #BLACK
skinparam noteTextAlignment left

Title: Family component command handling

participant ":XYZCommand" as Command COMMAND_COLOR

box
participant ":Family" as Family MODEL_COLOR
participant "parents:PersonList" as Parents MODEL_COLOR_T1
participant "myGen:PersonList" as MyGen MODEL_COLOR_T1
participant "children:PersonList" as Children MODEL_COLOR_T1
participant "Alice:Person" as Person MODEL_COLOR_T2
end box

participant ":System" as System LOGIC_COLOR
participant ":MoneyList" as Money MONEY_COLOR
participant ":UI" as UI UI_COLOR

