@startuml
!include style.puml

Package "Family" <<Rectangle>> {
    class Family MODEL_COLOR
    class PersonList MODEL_COLOR_T3
    class Person  MODEL_COLOR_T2
}

class Command COMMAND_COLOR
class Main #grey
class UI UI_COLOR
class Storage STORAGE_COLOR
class IncomeList MONEY_COLOR
class ExpenditureList MONEY_COLOR

Command -down[#grey].> Family

Main -down[#grey]-> Family

Storage "1" -down[#grey]-> "1" Family

Family "1" -down[#grey]-> "3" PersonList

Family -right[#grey].> UI

PersonList "1" -down[#grey]-> "*" Person

Person "1" -down[#grey]-> "1" IncomeList

Person -right[#grey].> UI

Person "1" -down[#grey]-> "1" ExpenditureList

@enduml