@startuml
actor user

user -> ":Ui" ++ : "free"
create ":Parser"
":Ui" -> ":Parser" ++: new Parser("free")
":Parser" --> ":Ui" --: parser:Parser
":Ui" -> ":Parser" ++: parseCommand()
create ":FreeCommand"
":Parser" -> ":FreeCommand" ++: new FreeCommand()
":FreeCommand" --> ":Parser" --: freeCommand:FreeCommand
":Parser" --> ":Ui" --: freeCommand:FreeCommand
":Ui" -> ":FreeCommand" ++: execute(masterTimetable)
":FreeCommand" -> ":MasterTimetable" ++: listBusy()
loop for each timetable
":MasterTimetable" -> ":Timetable" ++: populateBusySlots()
":Timetable" --> ":MasterTimetable" --
end
":MasterTimetable" --> ":FreeCommand" --: busySlots
":FreeCommand" -> ":FreeCommand"++: listFree(busySlots)
":FreeCommand" --> ":FreeCommand"--: freeTimeSlots
":FreeCommand" --> ":Ui" --: freeTimeSlots
":Ui" --> user
@enduml