 @startuml
 skinparam arrowThickness 1.1
 skinparam arrowColor black
 skinparam classBackgroundColor LOGIC_COLOR
 hide circle
package modules {

    Class Module {
        -moduleCode: String
        -category: String
        -day: String
        -timeSlot: String
        -moduleClassification: String
        -moduleCredits: Integer
    }

Class GradManager {
    -graduationList: Arraylist<Module>
    -totalCredits: Integer
    -electiveCredits: Integer
    -generalCredits: Integer
    -coreCredits: Integer
    -technicalCredits: Integer
}

Class ModuleCalendarReader
Class StudyManager
}

GradManager --> StudyManager

StudyManager --> ModuleCalendarReader : uses

ModuleCalendarReader --> Module

StudyManager *--> "*" Module : creates
 @enduml