@startuml
!include style.puml

box " " #WHITE
    participant "c:ListCatCommand" as Commands LOGIC_COLOR
    participant "<color:coral><<class>>\nParser" as Parser LOGIC_COLOR_T4
    participant ":Family" as Family MODEL_COLOR
    participant ":PersonList" as PList MODEL_COLOR
    participant ":Person" as Person MODEL_COLOR
    participant ":ExpenditureList" as MList MODEL_COLOR_T3
    participant ":Expense" as Money MODEL_COLOR_T3
    participant "<color:coral><<class>>\nUI" as UI UI_COLOR_T3
end box

[-> Commands : execute(listcat /c 1)
activate Commands

Commands -> Parser : parseCategory(listcat /c 1)
activate Parser
Parser --> Commands : 1
deactivate Parser


Commands -> Family : listExpenseOfCategory(1)
activate Family

loop for each Generation
    Family -> PList : getPersonList()
    activate PList
    PList --> Family
    deactivate PList

    loop for each Person
        Family -> Person : getPerson()
        activate Person
        Person --> Family : p
        deactivate Person

        Family -> MList : getExpenseOfCategory(1)
        activate MList

        loop for each expense
            MList -> Money : getCategory()
            activate Money
            Money --> MList
            deactivate Money
        end

        MList --> Family : ArrayList<Expenditure>
        deactivate MList
    end
end

Family -> UI : printMsg()
activate UI
UI --> Family
deactivate UI

Family --> Commands
deactivate Family

[<--Commands
deactivate Commands
@enduml
