@startuml
actor user

user -> ":Ui" ++ : "list all"
create ":Parser"
":Ui" -> ":Parser" ++: new Parser("list all")
":Parser" --> ":Ui" --: parser:Parser
":Ui" -> ":Parser" ++: parseCommand()
create ":ListCommand"
":Parser" -> ":ListCommand" ++: new ListCommand()
":ListCommand" --> ":Parser" --: listCommand:ListCommand
":Parser" --> ":Ui" --: listCommand:ListCommand
":Ui" -> ":ListCommand" ++: execute(masterTimetable)
":ListCommand" -> ":ListCommand"++: listAll(masterTimetable)
":ListCommand" -> ":MasterTimetable" ++: collateAll()
loop for each user
":MasterTimetable" -> ":ListCommand" ++: listUser(user, masterTimetable)
":ListCommand" -> ":Timetable" ++: sort()
":Timetable" --> ":ListCommand" --
":ListCommand" -> ":Timetable" ++: listTimetable()
":Timetable" --> ":ListCommand" --
":ListCommand" --> ":MasterTimetable" --
end
":MasterTimetable" --> ":ListCommand" --: str
":ListCommand" --> ":ListCommand" --: str
":ListCommand" --> ":Ui" --: str
":Ui" --> user
@enduml