@startuml
!include style.puml

box " "
    participant "c:ListExpCommand" as Commands COMMAND_COLOR_T1
    participant "<<Class>>\nParser" as Parser LOGIC_COLOR
    participant ":Family" as Family MODEL_COLOR
    participant ":PersonList" as PList MODEL_COLOR_T3
    participant ":Person" as Person MODEL_COLOR_T2
    participant ":ExpenditureList" as MList MONEY_COLOR
    participant ":Expenditure" as Money MONEY_COLOR_T1
    participant "<<Class>>\nUI" as UI UI_COLOR
end box

[-> Commands : execute("listexp /c 2")
activate Commands

Commands -> Parser : parseCategory(\n"listexp /c 2":String)
activate Parser
Parser --> Commands : 2:int
deactivate Parser


Commands -> Family : listExpenseOfCategory(2:int)
activate Family

loop for each Generation
    Family -> PList : listExpenseOf-\nCategory(2:int)
    activate PList

    loop LOOP_COLOR for each Person p
        PList -> Person : getPerson(p)
        activate Person
        Person --> PList : :Person
        deactivate Person

        PList -> MList : getExpenseOfCategory(2:int)
        activate MList

        loop for each expense
            MList -> Money : getCategory()
            activate Money
            Money --> MList
            deactivate Money
        end

        MList --> PList : :ArrayList<Expenditure>
        deactivate MList
    end
end

PList --> Family : :ArrayList\n<Expenditure>
deactivate PList

Family -> UI : printMsg()
activate UI
UI --> Family
deactivate UI

Family --> Commands
deactivate Family

[<--Commands
deactivate Commands
@enduml
