@startuml
!include style.puml

box " "
    participant "c:ListCatCommand" as Commands LOGIC_COLOR
    participant "<color:coral><<class>>\nParser" as Parser LOGIC_COLOR_T4
    participant ":Family" as Family MODEL_COLOR
    participant ":PersonList" as PList MODEL_COLOR
    participant ":Person" as Person MODEL_COLOR
    participant ":ExpenditureList" as MList MODEL_COLOR_T3
    participant ":Expenditure" as Money MODEL_COLOR_T3
    participant "<color:coral><<class>>\nUI" as UI UI_COLOR_T4
end box

[-> Commands : execute(listexp /c 2)
activate Commands

Commands -> Parser : parseCategory(listexp /c 2)
activate Parser
Parser --> Commands : 2:int
deactivate Parser


Commands -> Family : listExpenseOfCategory(2)
activate Family

loop for each Generation
    Family -> PList : listExpense-\nOfCategory(2)
    activate PList

    loop #honeydew for each Person p
        PList -> Person : getPerson(p)
        activate Person
        Person --> PList : :Person
        deactivate Person

        PList -> MList : getExpenseOfCategory(2)
        activate MList

        loop for each expense
            MList -> Money : getCategory()
            activate Money
            Money --> MList
            deactivate Money
        end

        MList --> PList : :ArrayList<Expenditure>
        deactivate MList
    end
end

PList --> Family : :ArrayList\n<Expenditure>
deactivate PList

Family -> UI : printMsg()
activate UI
UI --> Family
deactivate UI

Family --> Commands
deactivate Family

[<--Commands
deactivate Commands
@enduml
