@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
show members
hide empty members

title After iterating Alice's ExpenditureList

package " " {
    class temp as "__tempList:ExpenditureList__"
    class Fam as "__family:Family__"
    class MyGen as "__myGen:PersonList__"
    class Parent as "__parent:PersonList__"
    class Alice as "__Alice:Person__"
    class Bob as "__Bob:Person__"
    class List as "__:ExpenditureList__"
    class List2 as "__:ExpenditureList__"
    class Exp0 as "__:Expenditure__" #LIGHTGREEN {
        description = "Lunch"
        category = 1
    }
    class Exp1 as "__:Expenditure__" #LIGHTGREEN {
        description = "Dinner"
        category = 1
    }
    class Exp2 as "__:Expenditure__" #LIGHTGREEN {
        description = "Movies"
        category = 5
    }
    class Exp3 as "__:Expenditure__" #LIGHTGREEN {
        description = "Electric Bills"
        category = 2
    }
    class Exp4 as "__:Expenditure__" #LIGHTGREEN {
        description = "Lunch"
        category = 1
    }
    class Exp5 as "__:Expenditure__" #LIGHTGREEN {
        description = "Dinner"
        category = 1
    }
}

Fam -right-> Parent
Fam -down-> MyGen

Parent -right-> Bob
MyGen -> Alice

Alice -> List
Bob -> List2

Exp0 -up[#GREEN]-> List
Exp1 -up[#GREEN]-> List
Exp2 -up[#GREEN]-> List
Exp3 -up[#GREEN]-> List

Exp4 -down[#GREEN]-> temp
Exp5 -down[#GREEN]-> temp

temp-[HIDDEN]>Fam

Exp0 -right[HIDDEN]> Exp1
Exp1 -right[HIDDEN]> Exp2
Exp2 -right[HIDDEN]> Exp3

Exp4 -right[HIDDEN]> Exp5


@end