@startuml
'https://plantuml.com/sequence-diagram

skinparam guillemet false

mainframe sd Enter appropriate section depending on mode value
activate ":AllOnUs"
alt mode is contacts manager mode
    ":AllOnUs" -> "contactsManager:ContactsManager" ++: contactsRunner()
    "contactsManager:ContactsManager" --> ":AllOnUs" --
else mode is study manager mode
    ":AllOnUs" -> "studyManager:StudyManager" ++: studyManagerRunner()
    "studyManager:StudyManager" --> ":AllOnUs" --
else mode is expense tracker mode
    ":AllOnUs" -> "expenseTracker:ExpenseTracker" ++: expenseRunner()
    "expenseTracker:ExpenseTracker" --> ":AllOnUs" --

end
@enduml