@startuml
!include style.puml

Package "Money" <<Rectangle>> {
    abstract class Money MONEY_COLOR_T1
    abstract class MoneyList MONEY_COLOR
    class Income MONEY_COLOR_T1
    class IncomeList MONEY_COLOR
    class Expenditure MONEY_COLOR_T1
    class ExpenditureList MONEY_COLOR
}

Income --up[#grey]-|> Money
Expenditure --up[#grey]-|> Money

IncomeList --up[#grey]-|> MoneyList
ExpenditureList --up[#grey]-|> MoneyList

IncomeList "1" -down[#grey]-> "*" Income
ExpenditureList "1" -down[#grey]-> "*" Expenditure

@enduml