@startuml
!include style.puml
skinparam arrowColor #BLACK

Title : Execute(userInput) for "deletein /u 1 /g 2 /r 1"

box Parser LOGIC_COLOR_T1
Participant "<color:pink><<Class>>\nParser" as Parser LOGIC_COLOR_T4
Participant "<color:pink><<Class>>\nParserUtility" as UParser LOGIC_COLOR_T2
end box

box Family MODEL_COLOR_T1
Participant Family as ":Family" MODEL_COLOR
Participant PLIST as "myGen:PersonList" MODEL_COLOR
Participant Person as "Alice:Person" MODEL_COLOR
end box

box MoneyList #INDIANRED
Participant ILIST as ":IncomeList" #FIREBRICK
end box

[-> Parser : parseKeyword(userInput)
activate Parser
Parser -> UParser : parseDelimitedTerm(userInput, " ")
activate UParser
UParser --> Parser
deactivate UParser
Parser -->[ : "deletein":String
deactivate Parser

[-> Parser : parseUserIndex(userInput) 
activate Parser
Parser -> UParser : parseDelimitedTerm(userInput, "/u")
activate UParser
UParser --> Parser
deactivate UParser
Parser -->[ : "1":String
deactivate Parser

[-> Parser : parseGroupIndex(userInput) 
activate Parser
Parser -> UParser : parseDelimitedTerm(userInput, "/g")
activate UParser
UParser --> Parser
deactivate UParser
Parser -->[ : "2":String
deactivate Parser

[-> Parser : parseRecordIndex(userInput)
activate Parser
Parser -> UParser : parseDelimitedTerm(userInput, "/r")
activate UParser
UParser --> Parser
deactivate UParser
Parser -->[ : "1":String
deactivate Parser

[-> Parser : getValidGroupIndex("1")
activate Parser
Parser -> Family : getNumberOfGroups()
activate Family
Family --> Parser : maxIdx:int
deactivate Family
Parser -> UParser : checkTooHighIndex(1, maxIdx)
activate UParser
UParser --> Parser
deactivate UParser
Parser -> UParser : checkTooLowIndex(1, minIdx)
activate UParser
UParser --> Parser
deactivate UParser
Parser -->[ : 1:int
deactivate Parser

[-> Parser : getValidUserIndex("2", myGen)
activate Parser
Parser -> PLIST : getNumberOfMembers()
activate PLIST
PLIST --> Parser : maxIdx:int
deactivate PLIST
Parser -> UParser : checkTooHighIndex(2, maxIdx)
activate UParser
UParser --> Parser
deactivate UParser
Parser -> UParser : checkTooLowIndex(2, minIdx)
activate UParser
UParser --> Parser
deactivate UParser
Parser -->[ : 2:int
deactivate Parser

[-> Parser : getValidIncomeIndex("1", Alice)
activate Parser
Parser -> Person : getNumberOfIncomes()
activate Person
Person -> ILIST : getNumberOfIncomes()
activate ILIST
ILIST --> Person
deactivate ILIST
Person --> Parser  : maxIdx:int
deactivate Person
Parser -> UParser : checkTooHighIndex(1, maxIdx)
activate UParser
UParser --> Parser
deactivate UParser
Parser -> UParser : checkTooLowIndex(1, minIdx)
activate UParser
UParser --> Parser
deactivate UParser
Parser -->[ : 1:int
deactivate Parser

@enduml

