@startuml
!include style.puml
show members
hide empty members

title After user launches the application

package " " {
    class family as "__family:Family__" MODEL_COLOR
    class parents as "__parents:PersonList__" MODEL_COLOR_T1
    class myGen as "__myGen:PersonList__" MODEL_COLOR_T1
    class children as "__children:PersonList__" MODEL_COLOR_T1
}

family -down[#grey]-> parents
family -down[#grey]-> myGen
family -down[#grey]-> children

@enduml
