@startuml
hide footbox

!include style.puml

title When user calls "addin"

box
participant ":Command" as Command COMMAND_COLOR
participant ":Family" as Family MODEL_COLOR
participant ":PersonList" as PersonList MODEL_COLOR_T3
participant ":Person" as Person MODEL_COLOR_T2
participant ":IncomeList" as IncomeList MONEY_COLOR

[-> Command : execute(addin)
activate Command
Command -> Family : addin(group, personIndex, incomeInfo)
activate Family
Family -> PersonList : addin(personIndex, incomeInfo)
activate PersonList
PersonList -> Person : addin(incomeInfo)
activate Person
Person -> IncomeList : addin(incomeInfo)
activate IncomeList
Person <-- IncomeList
deactivate IncomeList
PersonList <-- Person
deactivate Person
Family <-- PersonList
deactivate PersonList
Command <-- Family
deactivate Family
[<--Command
deactivate Command

end box

@enduml