@startuml
'https://plantuml.com/sequence-diagram

Actor ":User" as user
participant ":UserInterface" as ui
participant ":Regex" as regex
participant ":Command" as command
participant ":Good" as good

user -> ui ++ : "remove id/id q/quantity"

ui -> regex  ++: Regex(regex, input)
regex -> ui -- : Hashmap of results

ui -> command ++ : removeGood(id, quantity, userGoods)
alt quantity input <= existing quantity
    command -> good ++ : reduce quantity of goods
    opt quantity input = existing quantity
        command ->x good : delete the goods
    end
else quantity input > existing quantity
    command -> good : do nothing
end
good --> command -- : the number of goods has been reduced
command --> ui -- : the number of goods has been reduced
ui --> user --: " `quantity` `name` have been removed "
@enduml