@startuml
'https://plantuml.com/sequence-diagram

hide footbox
actor User
participant ":MeetingJio"
participant ":Storage"
participant ":TextUi"

User -> ":MeetingJio" : exit
":MeetingJio" -> ":Storage"
":Storage" -> ":Storage" : SaveData()
":Storage" -> ":TextUi"
":TextUi" --> ":Storage" : Save_DATA_MESSAGE
":Storage" -> ":MeetingJio": Print(Save_DATA_MESSAGE)

@enduml