@startuml
!include style.puml

Box
    participant ":ExitCommand" as ExitCommand LOGIC_COLOR
    participant ":Storage" as Storage STORAGE_COLOR
    participant ":PersonList" as PersonList MODEL_COLOR
    participant PlanITarium.txt STORAGE_COLOR_T3
end box


-> ExitCommand: exit()
activate ExitCommand
ExitCommand -> Storage: saveData(:Family)
activate Storage
loop for all 3 family groups
Storage -> PersonList: getPersonList()
activate PersonList
PersonList --> Storage: :PersonList
deactivate PersonList
    loop until all items
        Storage -> PersonList: getSaveName()
        activate PersonList
        PersonList --> Storage: Name:Person
        deactivate PersonList
        Storage -> Storage: writeToFile()
        activate Storage
        Storage -> PlanITarium.txt
        activate PlanITarium.txt
        PlanITarium.txt --> Storage
        deactivate PlanITarium.txt
        Storage --> Storage
        deactivate Storage
        Storage -> PersonList: getIncomeList()
        activate Storage
        activate PersonList
        PersonList --> Storage: :IncomeList
        deactivate PersonList
        deactivate Storage
        Storage -> Storage: writeToFile()
        activate Storage
        Storage -> PlanITarium.txt
        activate PlanITarium.txt
        PlanITarium.txt --> Storage
        deactivate PlanITarium.txt
        Storage --> Storage
        deactivate Storage
        Storage -> PersonList: getExpenditureList()
        activate Storage
        activate PersonList
        PersonList --> Storage: :ExpenditureList
        deactivate PersonList
        deactivate Storage
        Storage -> Storage: writeToFile()
        activate Storage
        Storage -> PlanITarium.txt
        activate PlanITarium.txt
        PlanITarium.txt --> Storage
        deactivate PlanITarium.txt
        Storage --> Storage
        deactivate Storage
    end
end
Storage --> ExitCommand
deactivate Storage
<--ExitCommand
deactivate ExitCommand
@enduml