@startuml

!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package "Storage"<<Rectangle>>{

    Class Storage STORAGE_COLOR
    Class Family MODEL_COLOR
    Class Main #grey

}

Class "<$documents>" as File STORAGE_COLOR_T3
Storage -right[STORAGE_COLOR].> File
Main -right[#grey]-> "1" Storage
Storage -down[STORAGE_COLOR]-> "1" Family


@enduml