@startuml

hide footbox
skinparam SequenceReferenceBackgroundColor pink

participant ":InvMgr" as InvMgr
participant "storage:Storage" as Storage
participant "gson:Gson" as Gson

activate InvMgr
    InvMgr -> Storage : save(itemList: ItemList)
    activate Storage

        create Gson
        Storage -> Gson : Gson()
        activate Gson
        return

        Storage -> Gson : to(itemList)
        activate Gson
        return serializedItems: String

        ref over Storage
            Write serializedItems: String
            into dataFile
        end ref

    return itemList: ArrayList<Item>

@enduml
