@startuml
!include style.puml

Box
    participant Main UI_COLOR
    participant ":Storage" as Storage STORAGE_COLOR
    participant ":Family" as Family MODEL_COLOR
    participant ":PersonList" as PersonList MODEL_COLOR
    participant ":File" as File STORAGE_COLOR_T2
end box


-> Main: runs PlanITarium
activate Main
Main -> Storage: Initialise Storage Object
activate Storage
Storage --> Main: :Storage
deactivate Storage
Main -> Storage: loadData()
activate Storage
alt fileExists
else #pink notExist
    Storage -> File : createNewFile()
    activate File
    File --> Storage
    deactivate File
end
Storage -> Family: new()
activate Family
Family --> Storage : :Family
deactivate Family
loop until all logic groups are loaded
    Storage -> Storage: readSaveFile()
    activate Storage
    Storage -> Storage :addCorrespondingInfo()
    activate Storage
    Storage -> Family : addPersonList(:PersonList)
    activate Family
    Family -> PersonList: new()
    activate PersonList
    PersonList --> Family: :PersonList
    deactivate PersonList
    loop Until all items
        Family -> PersonList: addPerson(:Person)
        activate PersonList
        PersonList --> Family: :PersonList
        deactivate PersonList
    end
    Family --> Storage: :Family
    deactivate Family
    Storage --> Storage
    deactivate Storage
    Storage --> Storage
    deactivate Storage
end
Storage --> Main: :Family
deactivate Storage
<-- Main
deactivate Main

@enduml