@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide empty member

Class UserInterface {
    -warehouse : Warehouse
    -listParser : ListParser
    -viewParser : ViewParser
    -addParser : AddParser
    -removeParser : RemoveParser
    -totalParser : TotalParser
    -findParser : FindParser
    -helpParser : HelpParser
    -fulfillParser : FulfillParser
    +run() : void
}
@enduml