@startuml
hide circle
skinparam classAttributeIconSize 0
class Validator {
+minParameterCheck(String U, int): void
+validateAddAppointment(String(]): void
+validateDispenseMedicine(String(]): void
+validateEditAppointment(String(]): void
+validateFindAppointment(String]): void
+validateFindDoctor(String (]): void
+validateFindMedicine(String()]): void
+validateFindPatient (String I)]): void
+validateMedicine (String I]): void
+validateNric(String): void
+validateAddDoctor(String(): void
+validateAddPatient (String I]): void
-validateAddPerson (String I]): void
-validateAddress (String): void
-validateAdmissionDate(String): void
-validateAdmissionDob(String, String): void
-validateAge(String): void
-validateAppointmentDetails(String): void
-validateDate(String): boolean
-validateDate(String, String): void
-validateDob(String): void
-validateDobAge(String, String): void
-validateDosage(String): boolean
-validateExpiry(String): boolean
-validateFullName(String): void
-validateGender(String): void
-validateMedicineName(String): boolean
-validateQuantity(String): boolean
-validateSpecialization(String): void
}
@enduml