@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml

autonumber

title Sequence Diagram of `search /workout` Command

actor   User
participant "werkIt:WerkIt" AS WerkIt
participant "ui:UI" AS UI1
participant "parser:Parser" AS Parser
participant "newCommand\n:SearchCommand" AS newCommand
participant "workoutList\n:WorkoutList" AS WorkoutList

activate WerkIt
WerkIt -> UI1 : getUserInput()
activate UI1
User -> UI1 : `search /workout` command
WerkIt <-- UI1 : userInputTrimmed:String
deactivate UI1

WerkIt -> Parser : parseUserInput(userInput)
activate Parser
WerkIt <-- Parser : :Command
deactivate Parser

WerkIt -> newCommand : execute()
activate newCommand
newCommand -> WorkoutList : getWorkoutsDisplayList()
activate WorkoutList

newCommand <-- WorkoutList : "workoutList:ArrayList<String>"
deactivate WorkoutList

newCommand -> newCommand : searchWorkout()
User <-- newCommand : search outcome

deactivate newCommand

destroy newCommand
@enduml