@startuml
'https://plantuml.com/sequence-diagram
!include ../../Style.puml
hide footbox
autonumber

title Sequence Diagram of `search /exercise` Command

participant "werkIt:WerkIt" AS WerkIt
participant "ui:UI" AS UI1
participant "parser:Parser" AS Parser
participant "newCommand\n:SearchCommand" AS newCommand
participant "exerciseList\n:ExerciseList" AS ExerciseList

activate WerkIt
WerkIt -> UI1 : getUserInput()
activate UI1
WerkIt <-- UI1 : userInputTrimmed:String
deactivate UI1

WerkIt -> Parser : parseUserInput(userInput)
activate Parser
WerkIt <-- Parser : :Command
deactivate Parser

WerkIt -> newCommand : execute()
activate newCommand
newCommand -> ExerciseList : getExerciseList()
activate ExerciseList

newCommand <-- ExerciseList : "exerciseList:ArrayList<String>"
deactivate ExerciseList

newCommand -> newCommand : searchExercise()

deactivate newCommand

destroy newCommand
@enduml