@startuml
!include Style.puml

box AddCommand
participant ":Parser" as Parser PARSER_COLOUR
participant "Command:AddCommand" as AddCommand COMMANDS_COLOUR
end box
hide footbox

Parser -> AddCommand: AddCommand.executeCommand()
activate AddCommand COMMANDS_COLOUR

AddCommand -> AddCommand: addInput,expenditureList,creditCardList, incomeList
activate AddCommand COMMANDS_COLOUR
AddCommand --> AddCommand:
deactivate AddCommand

alt hasCreditCardFlag()
AddCommand -> AddCommand: addCreditCard()
activate AddCommand COMMANDS_COLOUR
AddCommand --> AddCommand:
deactivate AddCommand


else hasIncomeFlag()
AddCommand -> AddCommand: addIncome()
activate AddCommand COMMANDS_COLOUR
AddCommand --> AddCommand:
deactivate AddCommand

else else
AddCommand -> AddCommand: addExpenditure()
activate AddCommand COMMANDS_COLOUR
AddCommand --> AddCommand:
deactivate AddCommand COMMANDS_COLOUR
AddCommand --> Parser:
deactivate AddCommand COMMANDS_COLOUR
end

@enduml
