@startuml
!include Style.puml

box addCreditCard()
participant ":Parser" as Parser PARSER
participant "AddCommand:Command" as AddCommand COMMANDS
participant ":GeneralFunctions" as GeneralFunctions HELPER
participant ":CreditCard" as CreditCard USERFINANCIAL
participant ":CreditCardList" as CreditCardList DATA
end box

Parser -> AddCommand: AddCommand.executeCommand()
activate AddCommand

AddCommand -> AddCommand: addCreditCard()
activate AddCommand



AddCommand -> GeneralFunctions: parseInputWithCommandFlag()
activate GeneralFunctions
GeneralFunctions --> AddCommand: cardName, cashBack, cardLimit, cardBalance
deactivate GeneralFunctions

'AddCommand -> AddCommandInputTest: test(paymentMethod, category, description, amount)
'activate AddCommandInputTest
'AddCommandInputTest --> AddCommand
'deactivate AddCommandInputTest

'AddCommand -> GeneralFunctions: capitalise(paymentMethod, category)
'activate GeneralFunctions
'GeneralFunctions --> AddCommand: Capitalised paymentMethod and category
'deactivate GeneralFunctions

create CreditCard
AddCommand -> CreditCard: new CreditCard(cardName, cashBack, cardLimit, cardBalance)
activate CreditCard
CreditCard --> AddCommand
deactivate CreditCard

AddCommand -> CreditCardList: creditCardList.add(new CreditCard)
activate CreditCardList
CreditCardList --> AddCommand
deactivate CreditCardList

AddCommand -> AddCommand: print added credit card

AddCommand --> AddCommand:
deactivate AddCommand
AddCommand --> Parser:
deactivate AddCommand
@enduml
