@startuml
!include Style.puml

skinparam sequence {
ArrowColor black
participantBorderColor black
LifelineBorderColor black
boxBorderColor black
}

box addExpenditure()
participant ":MMM" as MMM MMM_COLOUR
participant "CommandType:AddCommand" as AddCommand COMMANDS_COLOUR
participant ":GeneralFunctions" as GeneralFunctions HELPER_COLOUR
participant ":AddCommandInputTest" as AddCommandInputTest HELPER_COLOUR
participant ":Expenditure" as Expenditure USERFINANCIAL_COLOUR
participant ":ExpenditureList" as ExpenditureList DATA_COLOUR
participant ":CreditCardList" as CreditCardList DATA_COLOUR
participant ":CreditCard" as CreditCard USERFINANCIAL_COLOUR
end box
hide footbox

MMM -> AddCommand: executeCommand()
activate AddCommand COMMANDS_COLOUR

AddCommand -> AddCommand: addExpenditure()
activate AddCommand COMMANDS_COLOUR

AddCommand -> GeneralFunctions: parseInputWithCommandFlag()
activate GeneralFunctions HELPER_COLOUR
GeneralFunctions --> AddCommand
deactivate GeneralFunctions


AddCommand -> AddCommandInputTest: testExpenditureParameters()
activate AddCommandInputTest HELPER_COLOUR

AddCommandInputTest --> AddCommand
deactivate AddCommandInputTest
AddCommand --> AddCommand
deactivate AddCommand COMMANDS_COLOUR

opt PAYMENT_METHOD == cash
AddCommand -> GeneralFunctions: capitalise(paymentMethod)
activate GeneralFunctions HELPER_COLOUR
GeneralFunctions --> AddCommand
deactivate GeneralFunctions
end
AddCommand -> GeneralFunctions: capitalise(category)
activate GeneralFunctions HELPER_COLOUR
GeneralFunctions --> AddCommand
deactivate GeneralFunctions

AddCommand -> GeneralFunctions: formatFloat(amount)
activate GeneralFunctions HELPER_COLOUR
GeneralFunctions --> AddCommand
deactivate GeneralFunctions

create Expenditure
AddCommand -> Expenditure: Expenditure()
activate Expenditure USERFINANCIAL_COLOUR
Expenditure --> AddCommand
deactivate Expenditure

AddCommand -> ExpenditureList: add()
activate ExpenditureList DATA_COLOUR
ExpenditureList --> AddCommand
deactivate ExpenditureList

note left
Details of newly added expenditure
is printed out
end note

opt PAYMENT_METHOD != cash

AddCommand -> AddCommand: updateCreditCardTotalExpenditure()
activate AddCommand COMMANDS_COLOUR
AddCommand -> CreditCardList: get()
activate CreditCardList DATA_COLOUR
CreditCardList --> AddCommand
deactivate CreditCardList

AddCommand -> CreditCard: addExpenditure(amount)
activate CreditCard USERFINANCIAL_COLOUR
CreditCard --> AddCommand
deactivate CreditCard

AddCommand --> AddCommand
deactivate AddCommand

end

AddCommand --> MMM
deactivate AddCommand
@enduml
