@startuml
!include Style.puml

box addExpenditure()
participant ":Parser" as Parser LOGIC_COLOR_T1
participant "Command:AddCommand" as AddCommand LOGIC_COLOR_T1
participant ":GeneralFunctions" as GeneralFunctions LOGIC_COLOR_T1
participant ":AddCommandInputTest" as AddCommandInputTest LOGIC_COLOR_T1
participant ":Expenditure" as Expenditure LOGIC_COLOR_T1
participant ":expenditureList" as expenditureList LOGIC_COLOR_T1
end box

Parser -> AddCommand: AddCommand.executeCommand()
activate AddCommand

AddCommand -> AddCommand: addExpenditure()
activate AddCommand



AddCommand -> GeneralFunctions: parseInputWithCommandFlag()
activate GeneralFunctions
GeneralFunctions --> AddCommand: paymentMethod, category, description, amount, time
deactivate GeneralFunctions

AddCommand -> AddCommandInputTest: test(paymentMethod, category, description, amount, creditCardList)
activate AddCommandInputTest
AddCommandInputTest --> AddCommand
deactivate AddCommandInputTest

AddCommand -> GeneralFunctions: capitalise(paymentMethod, category)
activate GeneralFunctions
GeneralFunctions --> AddCommand: Capitalised paymentMethod and category
deactivate GeneralFunctions

create Expenditure
AddCommand -> Expenditure: new Expenditure(paymentMethod, category, description, amount, time)
activate Expenditure
Expenditure --> AddCommand
deactivate Expenditure

AddCommand -> expenditureList: expenditureList.add(new Expenditure)
activate expenditureList
expenditureList --> AddCommand
deactivate expenditureList

AddCommand -> AddCommand: print added expenditure

AddCommand --> AddCommand:
deactivate AddCommand
AddCommand --> Parser: finishedMessage
deactivate AddCommand
@enduml
