@startuml
!include Style.puml

hide footbox
skinparam sequenceMessageAlign center

skinparam sequence {
ArrowColor black
participantBorderColor black
LifelineBorderColor black
boxBorderColor black
}

box addIncome()
participant ":MMM" as MMM MMM_COLOUR
participant "commandType:AddCommand" as C COMMANDS_COLOUR
participant ":GeneralFunctions" as GF HELPER_COLOUR
participant ":AddCommandInputTests" as IT HELPER_COLOUR
participant ":Income" as I USERFINANCIAL_COLOUR
participant ":IncomeList" as IL USERFINANCIAL_COLOUR
end box

activate MMM MMM_COLOUR
MMM -> C: executeCommand()

activate C COMMANDS_COLOUR
C -> C: addIncome()
activate C COMMANDS_COLOUR

C -> GF: parseInputWithCommandFlag()
activate GF HELPER_COLOUR
GF --> C
deactivate GF

C -> IT: testIncomeParameters()
activate IT HELPER_COLOUR

IT -> IT: testIncomeAmount()
activate IT HELPER_COLOUR
IT --> IT
deactivate IT HELPER_COLOUR

IT -> IT: testIncomeCategory()
activate IT HELPER_COLOUR
IT --> IT
deactivate IT HELPER_COLOUR

IT --> C
deactivate IT


create I
C -> I: Income()
activate I USERFINANCIAL_COLOUR
I --> C
deactivate

C -> IL: add()
activate IL USERFINANCIAL_COLOUR
IL --> C
deactivate

C --> C
deactivate

note left
Details of newly added
Income is printed out
end note

C --> MMM
deactivate

@enduml
