@startuml
!include Style.puml

box CalculateInputCommand
participant ":MMM" as MMM MMM_COLOUR
participant "Command:CalculateInputCommand" as CalculateInputCommand COMMANDS_COLOUR
participant ":Calculations" as Calculations USERFINANCIAL_COLOUR
participant ":GeneralFunctions" as GeneralFunctions  HELPER_COLOUR
end box
hide footbox

MMM -> CalculateInputCommand: CalculateInputCommand.executeCommand()
activate CalculateInputCommand COMMANDS_COLOUR

CalculateInputCommand -> GeneralFunctions: parseInput()
activate GeneralFunctions HELPER_COLOUR
GeneralFunctions --> CalculateInputCommand
deactivate GeneralFunctions HELPER_COLOUR


alt contain FLAG_OF_EXPENDITURE_PER_MONTH
CalculateInputCommand -> Calculations: calculateExpenditure()
activate CalculateInputCommand COMMANDS_COLOUR
activate Calculations USERFINANCIAL_COLOUR
Calculations -> GeneralFunctions: findItemInList()
activate GeneralFunctions HELPER_COLOUR
GeneralFunctions --> Calculations
deactivate GeneralFunctions HELPER_COLOUR
Calculations -> Calculations: displayCalculationBreakdown()
activate Calculations USERFINANCIAL_COLOUR
Calculations --> Calculations
deactivate Calculations HELPER_COLOUR
Calculations --> CalculateInputCommand
deactivate Calculations HELPER_COLOUR
CalculateInputCommand --> MMM
deactivate CalculateInputCommand COMMANDS_COLOUR


else
CalculateInputCommand --> MMM: MindMyMoneyException
deactivate CalculateInputCommand COMMANDS_COLOUR
end


@enduml