@startuml
!include Style.puml

hide footbox
skinparam sequenceMessageAlign center

skinparam sequence {
ArrowColor black
participantBorderColor black
LifelineBorderColor black
boxBorderColor black
}

box deleteCreditCard()
participant ":MMM" as MMM MMM_COLOUR
participant "CommandType:DeleteCommand" as C COMMANDS_COLOUR
participant ":CreditCardList" as CreditCardList DATA_COLOUR
end box

MMM -> C: executeCommand()
activate C COMMANDS_COLOUR

C -> C: deleteCreditCard()
activate C COMMANDS_COLOUR

C -> CreditCardList: delete()
activate CreditCardList DATA_COLOUR
CreditCardList --> C
deactivate CreditCardList

C --> C

note left
Details of deleted
Credit Card is printed out
end note

deactivate C

C --> MMM
deactivate C

@enduml
