@startuml
!include Style.puml

skinparam sequence {
ArrowColor black
participantBorderColor black
LifelineBorderColor black
boxBorderColor black
}

box Deserialize List
participant ":ExpenditureList" as ExpenditureList DATA_COLOUR
participant ":SerializerFunctions" as SerializerFunctions STORAGE_COLOUR
participant ":Expenditure" as Expenditure USERFINANCIAL_COLOUR
participant ":PropertyList" as PropertyList DATA_COLOUR
end box
hide footbox

[-> ExpenditureList : deserializeFrom()
activate ExpenditureList DATA_COLOUR
ExpenditureList -> SerializerFunctions : convertInputToList()
activate SerializerFunctions STORAGE_COLOUR
loop until end line is read
    SerializerFunctions -> Expenditure ** : deserialize()
    activate Expenditure USERFINANCIAL_COLOUR
    deactivate Expenditure

    Expenditure -> PropertyList ** : deserialize()
    activate PropertyList DATA_COLOUR
    deactivate PropertyList
    PropertyList --> Expenditure --
    Expenditure -> PropertyList: getValue()
    activate PropertyList DATA_COLOUR
    PropertyList --> Expenditure --

    Expenditure --> SerializerFunctions --
end
SerializerFunctions --> ExpenditureList --
[<-- ExpenditureList --

@enduml
