@startuml
!include Style.puml
'https://plantuml.com/sequence-diagram
box ListCommand
participant ":Parser" as Parser PARSER_COLOUR
participant "Command:ListCommand" as ListCommand COMMANDS_COLOUR
end box
activate ListCommand COMMANDS_COLOUR
ListCommand -> ListCommand: listToString()
activate ListCommand COMMANDS_COLOUR
ListCommand --> ListCommand: listInString:String
deactivate ListCommand

ListCommand --> Parser
deactivate ListCommand

@enduml
