@startuml
!include Style.puml

box Saving
participant ":MMM" as MMM MMM_COLOUR
participant ":Storage" as Storage STORAGE_COLOUR
participant ":User" as User USERFINANCIAL_COLOUR
participant ":ExpenditureList" as ExpenditureList USERFINANCIAL_COLOUR
participant ":CreditCardList" as CreditCardList USERFINANCIAL_COLOUR
participant ":IncomeList" as IncomeList USERFINANCIAL_COLOUR
end box

MMM -> Storage : save()
activate Storage STORAGE_COLOUR
Storage -> User : serialize()
activate User USERFINANCIAL_COLOUR
User -> ExpenditureList : serialize()
activate ExpenditureList USERFINANCIAL_COLOUR

ref over User, ExpenditureList : serialize list
ExpenditureList --> User --
User -> CreditCardList : serialize()
activate CreditCardList USERFINANCIAL_COLOUR

CreditCardList --> User --
User -> IncomeList : serialize()
activate IncomeList USERFINANCIAL_COLOUR

IncomeList --> User --
User --> Storage --
deactivate Storage
@enduml