@startuml
!include Style.puml

skinparam sequence {
ArrowColor black
participantBorderColor black
LifelineBorderColor black
boxBorderColor black
}

box Serialize List
participant ":ExpenditureList" as ExpenditureList DATA_COLOUR
participant ":SerializerFunctions" as SerializerFunctions STORAGE_COLOUR
participant ":Expenditure" as Expenditure USERFINANCIAL_COLOUR
participant ":PropertyList" as PropertyList DATA_COLOUR
end box
hide footbox

[-> ExpenditureList : serialize()
activate ExpenditureList DATA_COLOUR
ExpenditureList -> SerializerFunctions : addListToStringBuilder()
activate SerializerFunctions STORAGE_COLOUR
loop for each element in list
    SerializerFunctions -> Expenditure : serialize()
    activate Expenditure USERFINANCIAL_COLOUR

    Expenditure -> PropertyList ** : PropertyList()
    activate PropertyList DATA_COLOUR
    deactivate PropertyList
    PropertyList --> Expenditure --
    Expenditure -> PropertyList : setValue()
    activate PropertyList DATA_COLOUR
    PropertyList --> Expenditure --
    Expenditure -> PropertyList : serialize()
    activate PropertyList DATA_COLOUR
    PropertyList --> Expenditure --

    Expenditure --> SerializerFunctions --
end
SerializerFunctions --> ExpenditureList --
[<-- ExpenditureList --

@enduml
