@startuml
'https://plantuml.com/sequence-diagram

hide footbox

participant User as User
participant Main as Main
participant "<font color=red>**<<class>>** \nParser" as Parser
participant ":ShowCommand" as ShowCommand
participant "c:ShowCommand" as instanceShowCommand
participant "<font color=red>**<<class>>** \nTimetable" as Timetable

User -> Main: "show 25/5/2022"

activate Main

Main -> Parser: parseCommand("show 25/5/2022")
activate Parser
Parser -> Parser: prepareShow("25/5/2022")
activate Parser
Parser --> Parser:
deactivate Parser

Parser -> Parser: parseShowCommandOptions("25/5/2022")
activate Parser
create ShowCommand
Parser ->  ShowCommand: new ShowCommand(null, "25/5/2022")
activate ShowCommand
ShowCommand --> Parser: :ShowCommand
deactivate ShowCommand
Parser --> Parser
deactivate Parser

Parser --> Main: :ShowCommand
deactivate Parser

Main -> instanceShowCommand: execute(taskList, ui, storage)
activate instanceShowCommand
instanceShowCommand -> Timetable: showScheduleByDay(dateInput, filteredtasks, ui)
activate Timetable
Timetable -> Timetable: prepareTimetable(dateInput, filtererdTasks, ui)
activate Timetable
Timetable -> Timetable: printTimetable(day, date, filteredTasks, ui, taskLength, doOnDateLength, partitionLength)
activate Timetable
Timetable -> Timetable: printRow(colOne, colTwo, colThree, colFour, colFive, taskLength, doOnDateLength, i, ui)
activate Timetable
deactivate Timetable
Timetable --> Timetable
deactivate Timetable
Timetable --> Timetable
deactivate Timetable
Timetable --> Timetable

Timetable --> instanceShowCommand
deactivate Timetable

instanceShowCommand --> Main
deactivate instanceShowCommand

Main --> User
deactivate Main


@enduml