@startuml
skinparam maxMessageSize 100

hide footbox
participant "c:ShowCommand" as ShowCommand
participant "<font color=red>**<<class>>** \nTimetable" as Timetable
participant "TaskList" as TaskList
participant "<font color=red>**<<class>>** \nTimetablePrinting" as TimetablePrinting

ShowCommand -> Timetable: showScheduleByDay(dateInput: LocalDate, filteredtasks: ArrayList<Task>, ui: Ui)
activate Timetable

Timetable -> TaskList: getFilteredTasksByDate(dateInput: LocalDate)
activate TaskList
TaskList --> Timetable: filteredTasks: ArrayList<Task>
deactivate TaskList
destroy TaskList

Timetable -> Timetable: setTimetable(dateInput: LocalDate, filtererdTasks: ArrayList<Task>, ui: Ui)
activate Timetable
Timetable --> Timetable
deactivate Timetable
Timetable -> Timetable: printSchedule()
activate Timetable

Timetable -> TimetablePrinting: printTimetable(day: String, date: String, filteredTasks: ArrayList<Task>, ui: Ui, taskLength: long, doOnDateLength: long, partitionLength: long)
activate TimetablePrinting
TimetablePrinting -> TimetablePrinting: printRow(colOne: String, colTwo: String, colThree: String, colFour: String, colFive: String, taskLength: long, doOnDateLength: long, i: int, ui: Ui)
activate TimetablePrinting
TimetablePrinting --> TimetablePrinting
deactivate TimetablePrinting

TimetablePrinting --> Timetable
deactivate TimetablePrinting

Timetable --> Timetable
deactivate Timetable

Timetable --> ShowCommand
deactivate Timetable



@enduml