@startuml
'https://plantuml.com/sequence-diagram

hide footbox
participant Storage as "storage:Storage"
participant File as "<<class>>\nFile"
participant JSONObject as ":JSONObject"
participant JSONArray as "taskArray:JSONArray"
participant Parser as "<<class>>\nParser"
participant Task as "newTask:Task"
participant List as "taskList:TaskList"

[-> Storage ++: load(taskList: TaskList)

Storage -> File as "<<class>>\nFile" ++: readAllLines(saveFilePath)

File --> Storage --: fileContent

opt fileContent not empty
    create JSONObject
    Storage -> JSONObject ++: JSONObject(fileContent)
    JSONObject --> Storage --:

    Storage -> JSONObject ++:getJSONArray()

    create JSONArray
    JSONObject -> JSONArray ++:
    deactivate JSONObject

    JSONArray --> Storage --: taskArray

    loop all element in taskArray
        Storage -> Parser ++: parseSaveData(taskElement)

        create Task
        Parser -> Task ++: Task()

        Task --> Parser --

        Parser --> Storage --: task

        Storage -> List ++: addTask(task)
        List --> Storage --
    end
end
Storage -> Storage ++ : writeSavedData(taskList)
Storage --> Storage --
return taskList
@enduml