@startuml
participant User

User -> ":StudyCommand": start 1
activate ":StudyCommand"

":StudyCommand" -> "<<class>>\nParser": parseStudyMode(start 1)
activate "<<class>>\nParser"

"<<class>>\nParser" -> ":TimerLogic": callStartTimer()
activate ":TimerLogic"

":TimerLogic" -> ":Timer": startTimer
activate ":Timer"

par
":Timer" -> ":Timer": start
":Timer" --> ":TimerLogic"
end

par
":Timer" -> ":Timer": update
":TimerLogic" --> "<<class>>\nParser"
end

"<<class>>\nParser" --> ":StudyCommand"
deactivate "<<class>>\nParser"

":Timer" -> ":Timer": update

":StudyCommand" --> User

User -> ":StudyCommand": stop

":Timer" -> ":Timer": update

":StudyCommand" -> "<<class>>\nParser": parseStudyMode(stop)
activate "<<class>>\nParser"

"<<class>>\nParser" -> ":TimerLogic": callStopTimer()

":Timer" -> ":Timer": update

":TimerLogic" -> ":Timer": stopTimer

":Timer" -> ":Timer": stop

":Timer" --> ":TimerLogic"
deactivate ":Timer"

":TimerLogic" --> "<<class>>\nParser"

"<<class>>\nParser" --> ":StudyCommand"
deactivate "<<class>>\nParser"

":StudyCommand" --> User
@enduml