@startuml
'https://plantuml.com/sequence-diagram

skinparam shadowing false
participant ":TagCommand" as TagCommand

mainframe **sd** Execute Tag Operation

activate TagCommand

alt TagOp == add
TagCommand -> TagCommand:addTag(targetModule:Module)
activate TagCommand
TagCommand ->] :getTaskList()
TagCommand <-] ::TaskList
TagCommand ->] :addTag(tagDescription:String, taskIndex:int)
TagCommand <-] ::Task
return result

else TagOp == del
TagCommand -> TagCommand:removeTag(targetModule:Module))
activate TagCommand
TagCommand ->] :getTaskList()
TagCommand <-] ::TaskList
TagCommand ->] :delTag(tagDescription:String, taskIndex:int)
TagCommand <-] ::Task
return result

else else
[<-- TagCommand:e:ParseException

end

@enduml