package seedu.duke.status;

public enum Status {
    ADD_PATIENT_SUCCESS,
    ADD_DOCTOR_SUCCESS,
    ADD_MEDICINE_SUCCESS,
    DELETE_PATIENT_SUCCESS,
    DELETE_DOCTOR_SUCCESS,
    DELETE_MEDICINE_SUCCESS,
    EDIT_PATIENT_SUCCESS,
    EDIT_DOCTOR_SUCCESS,
    EDIT_MEDICINE_SUCCESS,
    VIEW_SUCCESS,
    PRINT_HELP,
    END_APP
}
