package seedu.duke.status;

/*
 * Holds SUCCESS messages
 */
public enum Status {
    ADD_PATIENT_SUCCESS,
    ADD_DOCTOR_SUCCESS,
    ADD_MEDICINE_SUCCESS,
    ADD_APPOINTMENT_SUCCESS,
    DELETE_PATIENT_SUCCESS,
    DELETE_DOCTOR_SUCCESS,
    DELETE_MEDICINE_SUCCESS,
    DELETE_APPOINTMENT_SUCCESS,
    EDIT_PATIENT_SUCCESS,
    EDIT_DOCTOR_SUCCESS,
    EDIT_MEDICINE_SUCCESS,
    EDIT_APPOINTMENT_SUCCESS,
    UPDATE_MEDICINE_INVENTORY_SUCCESS,
    CLEAR_EXPIRED_MEDICINE_SUCCESS,
    VIEW_SUCCESS,
    PRINT_HELP,
    END_APP,
    FIND_DOCTOR_SUCCESS,
    FIND_MEDICINE_SUCCESS,
    FIND_PATIENT_SUCCESS,
    APPOINTMENT_FOUND_SUCCESS,
    MEDICINE_STOCK_FOUND_SUCCESS,
    DISPENSE_SUCCESS
}
