'Colour Constants
!define COLOR_LOGIC #LightSkyBlue
!define COLOR_PARSER #Gold
!define COLOR_UI #YellowGreen
!define COLOR_WERKIT #SandyBrown
!define COLOR_STORAGE #FF6961
!define COLOR_MAIN #Cornsilk

'General Settings
skinparam arrowColor #Black

'Class Diagram Settings
skinparam classBorderColor #Black

'Sequence Diagram Settings
