!define COLOR_LOGIC #LightSkyBlue
!define COLOR_PARSER #Gold
!define COLOR_UI #YellowGreen
!define COLOR_WERKIT #SandyBrown
!define COLOR_STORAGE #FF6961
!define COLOR_MAIN #Cornsilk

skinparam arrowColor #Black
skinparam classBorderColor #Black
