@startuml
'https://plantuml.com/sequence-diagram


User -> ":Duke": bye
":Duke" -> ":parser": getCommand()
":parser" --> ":Duke": fullCommand
":Duke" -> ":Ui": sayGoodbye()
":Ui" --> ":Duke": Goodbye message
":Duke" --> User: Goodbye message


@enduml