@startuml
'https://plantuml.com/class-diagram
package command {
    abstract class Command
    class DeleteCommand

    Command <|-- DeleteCommand
    Command <|-- ExitCommand
    DeleteCommand ..> CommandResult :creates >
    ExitCommand ..> CommandResult :creates >

    abstract class Command {
        +execute(): CommandResult {abstract}
    }

    class DeleteCommand {
    -moduleCode: String
    -taskModule: String
    -taskIndex: int
    +DeleteCommand(String moduleCode)
    +DeleteCommand(int taskIndex, String taskModule)
    +execute(): CommandResult
    }

    class ExitCommand {
    +execute(): CommandResult
    }

    class CommandResult {
    +CommandResult(String result)
    +toString(): String
    }
}

note top of command
Note:
This class diagram only illustrates two
example command types for simplicity.
end note

@enduml