@startuml
'https://plantuml.com/sequence-diagram

hide footbox
participant Storage as "storage:Storage"
participant UI as "ui:Ui"
participant System as "<<class>>\nSystem"

[-> Storage ++:handleCorruptedSave()
loop input not y or n
    Storage -> UI ++:readCommand()
    UI --> Storage --: input
    alt input = n
        Storage -> System ++: exit()
        return
    else
        Storage -> Storage ++: wipeSaveData()
        return
    end
end
return

@enduml