@startuml
'https://plantuml.com/class-diagram

!include Style.puml

package command {
    class "{abstract}\n Command "
    class DeleteCommand

    "{abstract}\n Command " <|-- DeleteCommand
    "{abstract}\n Command " <|-- ExitCommand
    DeleteCommand ..> CommandResult :creates >
    ExitCommand ..> CommandResult :creates >

    class "{abstract}\n Command " {
        +execute(): CommandResult {abstract}
    }

    class DeleteCommand {
    -moduleCode: String
    -taskModule: String
    -taskIndex: int
    +DeleteCommand(moduleCode: String)
    +DeleteCommand(taskModule: String, index: int)
    +execute(): CommandResult
    }

    class ExitCommand {
    +execute(): CommandResult
    }

    class CommandResult {
    +CommandResult(result: String)
    +toString(): String
    }
}

note top of command
Note:
This class diagram only illustrates two
example command types for simplicity.
end note

note left of DeleteCommand
Note:
getUserConfirmation() is intentionally
omitted as the dependency of DeleteCommand
on TextUi is a unique case in Commands.
end note

@enduml